### PR TITLE
ziafazal/YONK-321:move progress app under edxsolutions

### PR DESCRIPTION
**Pull request by ziafazal**
As a part of consolidation work we are moving edx solutions apps under their own directory edxsolution. This PR has relevant changes to move `progress` under `edxsolutions` and some fixes for quality violations. 

@douglashall would you please review this one?

### CODE REVIEW

**Comment by ziafazal** [comment]
@douglashall please review this one.

**Comment by douglashall** [comment]
@ziafazal Apologies for the delay. I will take a look at this one today.

**Comment by douglashall** [comment]
@ziafazal What is the value added by making this change? Wouldn't it be better to move the `progress` app to a separate repo, make in an installable python package, and require it in edx-platform?

**Comment by ziafazal** [comment]
@douglashall our eventual goal is to have a separate IDA for solutions apps. But we are going to achieve it in steps.
Step 1) Move all edx solutions apps under edxsolutions namespace
Step 2) Remove edx-platform dependencies of solutions apps and make sure all the interaction between solutions apps and edx-platform is done through api_manager(orchestration layer)
Step 3) Make edxsolutions an IDA
You can find more about it in comments of [YONK-313](https://openedx.atlassian.net/browse/YONK-313)

**Comment by douglashall** [comment]
@ziafazal I guess I'm just not sure how Step 1 gets us closer to or is required for Step 3.

**Comment by ziafazal** [comment]
@douglashall we have customized edx solutions app scattered over lms/djangoapp and openedx/djangoapp. Purpose of Step 1 was to consolidate them under one namespace or in other words separate them from open edx LMS djangoapps.

**Comment by douglashall** [comment]
@ziafazal Right, but if the goal is to create a separate IDA, does this consolidation here get us any closer to that end goal? Why not start by consolidating to a separate repo?

**Comment by ziafazal** [comment]
closing this in favour of PR #705.

**Pull request closed without merging**
