### PR TITLE
Version update: Problem Builder

### PR DESCRIPTION
**Pull request by e-kolpakov**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @e-kolpakov! I've created [OSPR-2234](https://openedx.atlassian.net/browse/OSPR-2234) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by e-kolpakov** [comment]
@bradenmacdonald or @tomaszgy please review

**Comment by e-kolpakov** [comment]
Build failure is unrelated, cannot retrigger as we don't have write access (and rights to trigger builds) anymore. 

@ziafazal Could you please review this PR and retrigger the build?

CC @bradenmacdonald, @tomaszgy

**Comment by ziafazal** [comment]
@e-kolpakov you should have right to retrigger. You have to login with your github account on Circle CI before it would allow you to retrigger.

**Comment by e-kolpakov** [comment]
@ziafazal oh, ok, thanks - didn't know that. Retriggered the build just now.

**Comment by bradenmacdonald** [comment]
Build failed again with the same old translation errors we keep seeing - trying to Rebuild without cache to see if that helps.

**Pull request merged**
