### PR TITLE
fixed issues with organization metrics when organization has multiple courses

### PR DESCRIPTION
**Pull request by ziafazal**
@mattdrayer @martynjames @markoivanovic I have made these fixes to address issues raised in MCKIN-2948 and MCKIN-2955.

### CODE REVIEW

**Comment by martynjames** [comment]
@marjev - Can you see if this meets your needs?

**Comment by marjev** [comment]
lgtm

**Comment by martynjames** [comment]
@mattdrayer, @ziafazal - @marjev likes the look of this, can we merge?

**Comment by mattdrayer** [comment]
Merging based on approval from @martynjames and @marjev

**Pull request merged**
