### PR TITLE
Update version of xblock-drag-and-drop-v2

### PR DESCRIPTION
**Pull request by kaizoku**
This simply updates the version of xblock-drag-and-drop-v2 to the latest.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @kaizoku! I've created [OSPR-3750](https://openedx.atlassian.net/browse/OSPR-3750) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@kaizoku Will you need edX review for this PR?

**Comment by kaizoku** [comment]
@natabene, we won't need one for this PR, it's just meant to update the version of `xblock-drag-and-drop-v2` to include our changes from https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/214.

We do have a PR for `xblock-drag-and-drop-v2` against the master branch that will need upstream review though: https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/211

**Comment by moeez96** [comment]
@xitij2000 is this commit intentionally merged to master or was that a mistake? Please comment
Cc: @kaizoku @naeem91 @ihtram

**Comment by xitij2000** [comment]
@moeez96  Sorry I did not notice the incorrect branch here. This was supposed to be merged to development.

**Comment by ihtram** [comment]
@xitij2000 can you please revert this commit from master?

**Pull request merged**
