### PR TITLE
Aggregation integration tests

### PR DESCRIPTION
**Pull request by jcdyer**
Create aggregation integration tests.  

These are moved over from edx/edx-platform#17703, because it was too hard to keep them in sync with the changing platform, and there was no good end plan for merging the code.  Here, it can be merged cleanly, and run with regular platform tests.

**JIRA tickets**: [BB-157](https://opencraft.atlassian.net/browse/BB-157/), [BB-163](https://opencraft.atlassian.net/browse/BB-163/)

**Discussions**: See references JIRA tickets, and mainline edx-platform PR.

**Dependencies**: None

**Screenshots**:

**Sandbox URL**: TBD - sandbox is being provisioned.

**Merge deadline**: None

**Testing instructions**:

1. Read over the discussion on the previous PR (edx/edx-platform#17703) and the referenced tickets.  
2. Verify that the tests provide sufficient coverage as described in [BB-163](https://opencraft.atlassian.net/browse/BB-163/).

**Author notes and concerns**:

**Reviewers**
- [ ] (OpenCraft internal reviewer's GitHub username goes here)
- [ ] edX reviewer[s] TBD

**Settings**
N/A

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @jcdyer! I've created [OSPR-2838](https://openedx.atlassian.net/browse/OSPR-2838) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by Metfriet** [comment]
@jcdyer Are you checking for BlockCompletions submitted in various configurations? I can't find it in the code, but maybe I am overlooking something.

**Comment by jcdyer** [comment]
@Metfriet I added some tests to verify the behavior of different configurations.

**Comment by Metfriet** [comment]
@jcdyer ok it looks good now. I will approve it when circleci is done.

**Comment by jcdyer** [comment]
Oh weird.  Those are passing for me locally.

**Comment by jcdyer** [comment]
That took longer to diagnose than it should.  The tests are passing on lms, but not cms.  They need to be flagged `@skip_unless_lms`.

**Comment by wajeeha-khalid** [comment]
@jcdyer can you please provide MCKIN lira ticket number against this work? I need this info to prepare release

**Comment by jcdyer** [comment]
This did not have a MCKIN ticket, so I've created one at https://edx-wiki.atlassian.net/browse/MCKIN-9091.  The only modifications here are adding tests (and fixing one tiny configuration error in LibraryContent module that was caught by the tests).

**Pull request merged**
