### PR TITLE
Remove extraneous width setting from .response-header-actions

### PR DESCRIPTION
**Pull request by Kelketek**
@bradenmacdonald

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
:+1:  Fix looks good. I tested in Apros and the LMS and confirmed this fixed part 1 of YONK-198. The second part (weird appearance of the hover effect on the reply voting button until you click it) is an upstream issue and this doesn't address it.

**Comment by Kelketek** [comment]
@feanil @fredsmith @maxrothman Whichever of you gets to this first-- all of the other current changes are in the release branches for Apros and Edx-platform. This is the only one that is missing. I'm tagging you all on it so that you know to pull in this commit into the release branch as soon as it's reviewed by @smarnach, @chrisndodge or someone else, in case I'm sleeping when that happens.

**Comment by chrisndodge** [comment]
@smarnach you might better insight here than I, but I'll trust everyone's judgement here to move forward.

**Comment by smarnach** [comment]
:+1: I tested this on Apros only, and it works fine.

**Pull request merged**
