### PR TITLE
Removed local overrides for discussion

### PR DESCRIPTION
**Pull request by e-kolpakov**

### CODE REVIEW

**Comment by Kelketek** [comment]
:+1:

**Comment by bradenmacdonald** [comment]
This change breaks the discussion XBlock in Apros for me.

Before this change, when I click "Show Discussion" on an inline Discussion XBlock, my browser issues `GET /courses/BradenX/101/2015/discussion/forum/e9f33a7fcf4b4eb3896361762b7cac6c/inline?page=1&ajax=1 HTTP/1.1` which returns some JSON and then the discussion appears.

After this change, when I click "Show Discussion", my browser issues the exact same GET request, but it gets back a generic Apros HTML page, and not JSON. So the discussion XBlock shows an error message and the discussion never loads.

LMS still works fine.

(I don't think this is relevant but I'll mention it in case: I'm *not* using the production static files settings (nothing about static assets in my nginx config), I'm using the django development static files server which is working perfectly well until this change.)

**Comment by e-kolpakov** [comment]
@bradenmacdonald there are some production rules in place that make it possible. Most likely you didn't notice, that before the change request went straight to LMS domain (`lms.mcka.local` in my case), but now it goes to Apros domain (`apros.mcka.local` in my case). This is intentional as it replicates production setup; there are some rules in nginx apros config that redirect xblock and discussion requests to lms.

I can see only two options here: either send requests directly to LMS, or do some routing via nginx. I was asked to remove local overrides, and detecting hostname is actually one of them. It was introduced long before, but in my opinion it does not make its existence lawful. 

@antoviaque @Kelketek I would love to hear your opinions on removing hostname detection from discussion.

**Comment by antoviaque** [comment]
@e-kolpakov I would be fine keeping the hostname declaration, and only removing the local overrides - my issue with the overrides is that it breaks the self-containment of XBlocks (ie code external to the xblock that runs instructions internal to the XBlock logic), that it makes it runtime-dependent, and that it broke the jquery-xblock abstraction layer (introduced instructions for a specific XBlock). The hostname detection doesn't do any of these - it is run by the XBlock itself, is runtime-independent (ie the code would work correctly from the LMS too - it just says "assume that the discussion resources are on the same domain as the XBlock ajax endpoint"), and it doesn't break the jquery-xblock abstraction layer.

**Comment by e-kolpakov** [comment]
@bradenmacdonald @antoviaque the problem here is that if we are to keep that detection, user profile links use LMS host explicitly, thus skipping nginx rules set up in production to redirect them to Apros. So, there need to be some other mechanism to specify URLs that should not use detected host, but point somewhere else (relative URL in this case). So, unfortunately I can't see how this can be achieved, except for (1) local runtime-specific override (which we are removing) or (2) always using relative URLs and let nginx sort it out (as in this PR and in production). Sorry for not mentioning this earlier, I had to dig down a bit to recall this.

There possibly could be other workarounds around this problem (i.e. have user profile links relevant, while other urls use hostname detection), but I haven't invented any yet, and most likely they will be just as workaroundish as local runtime-specific overrides.

@bradenmacdonald @antoviaque having heard that (and keeping in mind deadlines), do you still want me to think of some other approach here?

**Comment by antoviaque** [comment]
@bradenmacdonald The rules for the profile only applies to a specific case, and it doesn't affect production which has the LMS configured to point to the same domain, right? If so I would still keep that detection. There are disadvantages to both options in local dev (either making it harder to setup initially if we don't keep it, or having discrepancies with the production environment if we do), but it would still be possible to setup the local dev like the production instance for the tasks that do require it, but it makes things easier for the rest of the cases. Would that make sense?

**Comment by e-kolpakov** [comment]
@antoviaque I can't tell from ansible files if LMS configured to be on the same host+port or not. If I'm not mistaking you can't run two sites on the same port with same (virtual) server name, in which case rules configured for one virtual server won't affect request heading directly to other virtual server.

If you happen to have some time  now we could discuss on it irc.

**Comment by antoviaque** [comment]
@e-kolpakov You can do it via nginx, which acts as a reverse proxy binding different paths to different services. That's actually the main role of that nginx rules config file - it's on a single domain/host, selecting which service to send the requests to depending on the path.

I've just logged in on IRC, don't hesitate to ask me there as needed.

**Comment by e-kolpakov** [comment]
@bradenmacdonald @Kelketek restored hostname detection, please review again.

CC @antoviaque

**Comment by bradenmacdonald** [comment]
@e-kolpakov I only tested this on development mode, but I am happy now because it works :) :+1: If you or @Kelketek want me to test the two production configs as well, let me know.

**Comment by Kelketek** [comment]
:+1:

**Pull request merged**
