### PR TITLE
Update version for drag-and-drop-v2

### PR DESCRIPTION
**Pull request by kaizoku**
This simply updates the version of xblock-drag-and-drop-v2 to the latest.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @kaizoku! I've created [OSPR-3791](https://openedx.atlassian.net/browse/OSPR-3791) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@kaizoku Thank you for your contribution, will you need edX review?

**Comment by natabene** [comment]
@kaizoku Do you need edX review for this?

**Comment by natabene** [comment]
@kaizoku Is this PR still relevant?

**Comment by pomegranited** [comment]
@natabene  Yes, @kaizoku confirms that this PR is still relevant.  He's setting up a new sandbox so it can be tested, so will ping you here when this is ready.

**Comment by pomegranited** [comment]
@kaizoku  Nudge ^

**Comment by kaizoku** [comment]
@davidjoy, this was pending review on https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/211, which we've just received a final review on. I'll update and ping here once we confirm the merge with the new correct version for this.

**Comment by kaizoku** [comment]
@davidjoy, looks like we won't need a version bump for this after all. Thanks for following up on this one. I'll close this PR.

**Pull request closed without merging**
