### PR TITLE
[MCKIN-26432] Add back unit to Studio breadcrumbs UI

### PR DESCRIPTION
**Pull request by xitij2000**
Cherry-pick of https://github.com/edx/edx-platform/pull/25537

### CODE REVIEW

**Comment by xitij2000** [comment]
@ihtram This PR is a cherry-pick from our master PR where all tests are passing. If it seems OK, please feel free to merge.

**Comment by ihtram** [comment]
@xitij2000 It seems like the cherry picked PR has not been approved yet. Let's wait for the approval of that PR first.

**Comment by xitij2000** [comment]
@ihtram  It has been tested internally at OpenCraft, but we can wait for edX approval if that can happen within the timeline.

**Comment by xitij2000** [comment]
@ihtram This PR has been updated to be up to date with the upstream PR.

**Comment by ihtram** [comment]
@xitij2000 It seems like CircleCi tests are failing for this PR. Two of four containers are failing(0 and 3) please ignore the first one(0) but all other tests should pass. The failed test could be a ripple of your changes. Please pull latest code for idx-platform and all extension apps and then try running the failed tests on local environment.

**Comment by xitij2000** [comment]
@ihtram  I've rebased the code.

**Review by ihtram — APPROVED** [review]
LGTM. You can merge it. It would be great to keep an on upstream PR for any further recommendations or improvements.

**Comment by xitij2000** [comment]
> LGTM. You can merge it. It would be great to keep an on upstream PR for any further recommendations or improvements.

Sure, definitely. In such cases, we keep our internal ticket open till both PRs are merged and then make sure they are in sync.

**Pull request merged**
