### PR TITLE
Hash Update #3: Diagnostic-Feedback

### PR DESCRIPTION
**Pull request by jareerahsan**

### CODE REVIEW

**Comment by antoviaque** [comment]
@jareerahsan Have the changes corresponding to this hash update been reviewed?

**Comment by jareerahsan** [comment]
@antoviaque No, this was a feature update within the reviewed structure of the xblock, still following the feedback by your team, and @zvishal gave us a go ahead for merging this directly in leue of the extremely short deadline. However, I can edit this back to previous hash if it is required. Otherwise, if anyone from your team can review the changes, we would happily update the code to meet your feedback.

**Comment by antoviaque** [comment]
@jareerahsan @zvishal It's probably worth discussing this at our next standup - I don't really make the rules for this - for example the 2 reviewers requirements on edx-solutions repos come from edX, and we also have to conform to it ourselves.

**Comment by jareerahsan** [comment]
@antoviaque yes, sounds good, and I am sorry about the other change in repo for OPTIONAL_APPS, that was my mistake. @zvishal didn't give me a go ahead for that. We can revert it if it makes sense.

**Comment by antoviaque** [comment]
@jareerahsan No worries, you didn't knew - as long as it's done in the future it should be fine. Btw do you have reviewers from Arbisoft that you can ask for reviews?

**Comment by jareerahsan** [comment]
@antoviaque Definitely, I'll make sure of that. Yes, I was just able to get one review from here on the commons.py PR.

**Pull request merged**
