### PR TITLE
Moved solutions student migrations to top of migrations list.

### PR DESCRIPTION
**Pull request by Kelketek**
These migrations were out of order for playing atop birch.

### CODE REVIEW

**Comment by smarnach** [comment]
:+1: Looks good, and it worked for me.

**Comment by bradenmacdonald** [comment]
:+1: But you should ping the solutions/ops team before merging. Anyone who is already running a solutions instance will need to manually fix their local migrations:

```
rm ~/edx-platform/common/djangoapps/student/migrations/*.pyc
./manage.py lms --settings=devstack migrate student --delete-ghost-migrations --traceback --pythonpath=.
./manage.py lms --settings=devstack migrate student 0044 --fake --traceback --pythonpath=.
```

**Comment by smagoun** [comment]
@fredsmith @ziafazal please review this. I am surprised this wasn't necessary for the birch rebase. Please confirm that there are no other concerns about the migrations for birch.

**Comment by ziafazal** [comment]
what is the purpose of this PR?

**Comment by Kelketek** [comment]
@ziafazal It is not currently possible to provision the birch devstack, checkout the solutions master, and then run the migrations cleanly. This fixes that.

**Comment by ziafazal** [comment]
@Kelketek I would recommend using `--merge` option to run out of order migrations or manually merge those migrations instead of renaming migrations because renaming migrations would create problems in scenarios where they are already applied and secondly chances are it would distort the [frozen state](http://south.readthedocs.org/en/latest/ormfreezing.html) of ORM.

**Comment by Kelketek** [comment]
@ziafazal I'm going to take your advice and use --merge here. This issue will probably have to be revisted if we ever merge these features upstream, but today is not that day. We'd end up doing this every rebase, and it would be better to just do it once when we send them upstream than each time.

**Pull request closed without merging**
