### PR TITLE
Scorm Xblock and SSLA player

### PR DESCRIPTION
**Pull request by wajeeha-khalid**
@ziafazal Please review according to https://github.com/appsembler/edx_xblock_scorm/blob/nyif/master/README.md

Once this PR is good to go; I will be asking Fred to add following settings in `lms.env.json` and `cms.env.json` under `XBLOCK_SETTINGS` where `location` will be the location of SCORM JCA player package files that i have added as part of this PR

> "ScormXBlock": {
    "SCORM_PLAYER_BACKENDS": {
      "ssla": {
        "name": "SSLA",
        "location": "/edx-platform/static/scorm/ssla/player.htm",
        "configuration": {}
      }
    },
    "SCORM_PKG_STORAGE_DIR": "scorms"
  }

Please let me know if it does not make sense.

### CODE REVIEW

**Comment by ziafazal** [comment]
@wajeeha-khalid I think we should remove the `srorm/docs`, `scorm/install` and `scorm/ssla/player-aicc` directories. Other than that LGTM.

**Comment by wajeeha-khalid** [comment]
@ziafazal You are right; thanks for pointing this out.
I am not sure about `scorm/ssla/player-aicc`; could you please elaborate a little more around it. What purpose could it have and why these are not required for us?

**Comment by ziafazal** [comment]
@wajeeha-khalid it appears`player-aicc` has scripts to convert AICC based course data to SCORM complaint data. I don't think we need those scripts. One of them is a php script which can be a security risk.

**Comment by wajeeha-khalid** [comment]
@ziafazal Got it, thanks for explaining. I have updated this by removing requested unnecessary files. Let me know if its good to get merged.

**Pull request merged**
