### PR TITLE
clean up unnecessary migration

### PR DESCRIPTION
**Pull request by fredsmith**
This migration is duplicated in the organization application.  @mattdrayer @ziafazal

### CODE REVIEW

**Comment by mattdrayer** [comment]
:+1: from me, although we should check with @ziafazal to make sure it wasn't included on purpose (and thus should be renamed) -- although I agree in this case the migration does appear to be redundant with what is in the organizations app.

**Comment by ziafazal** [comment]
this migration removes `organizations` app related tables from `api_manager` since we have moved `organizations` app out of api_manager. I think right approach here would be either remove these migrations also
0008_organizations.py
0010_auto__add_field_organization_display_name__add_field_organization_cont.py
0011_auto__add_coursemodulecompletion.py
0013_auto__add_field_organization_logo_url.py
(these are responsible for creating organizations tables inside api_manager)
OR
keep this migration and rename it if its name is causing problems while running migrations.

**Comment by fredsmith** [comment]
@ziafazal - this migration fails because the table it tries to delete has already been deleted by the organizations migration.

In my opinion, the migration in the organizations app that deletes the api_manager_organizations table shouldn't be there.

**Comment by ziafazal** [comment]
@fredsmith yeah that is good idea to delete `0002_migrateorgdata.py` inside organizations. This migration is responsible for moving data from `api_manager.organizations` to `organizations` app which we no longer need.

**Comment by fredsmith** [comment]
I think moving data to the organizations table should still be done by the organizations app, but deleting the table in the api_manager app should not be done by the organizations app.

**Comment by ziafazal** [comment]
@fredsmith :+1: this migration was added by mistake i think. Let's merge this PR to remove it.

**Comment by mattdrayer** [comment]
Hi guys -- I think this particular PR should be reverted.  The problem stems from a duplicate commit that is currently present in master (from 10/27/2014) which undoes the subsequent change made on 10/30/2014.

The organizations app needs to be the one to remove the api_manager_organizations table -- it's the only thing that knows when the data has been migrated from api_manager to organizations.  If the api_manager were in charge of removing that table, then South would remove the table prior to the migration of the data (A before O).  If the api_manager app were in charge of the full migration, it's possible that the organizations app would not exist (it's an optional installation), so the migration would bomb.  So the organizations app needs to be in charge of creating its tables, migrating state to them, and cleaning up the remnants from the rest of the system.

**Comment by mattdrayer** [comment]
So just to clarify -- we need to remove/revert/undo the extra 'initial changes' commit here:  https://github.com/edx-solutions/edx-platform/commits/master/lms/djangoapps/api_manager/migrations

**Comment by fredsmith** [comment]
@mattdrayer reverted with PR #438 -  I agree with you, applications should not be changing each other's tablespaces.

**Pull request merged**
