### PR TITLE
Update hash: Added Group Project V2 to list of required XBlocks

### PR DESCRIPTION
**Pull request by e-kolpakov**

### CODE REVIEW

**Comment by Kelketek** [comment]
@e-kolpakov When I try to run `paver install_prereqs` with this, I get:

```
fatal: reference is not a tree: be40cc50b69d9532f73dc6d4e2ac45570125ad65
Command /usr/bin/git checkout -q be40cc50b69d9532f73dc6d4e2ac45570125ad65 failed with error code 128 in /edx/app/edxapp/venvs/edxapp/src/xblock-group-project-v2
```

**Comment by e-kolpakov** [comment]
@Kelketek I've noticed a development leftover in template and decided it would make sense to remove it completely. So I did a rebase, than force pushed group-project-v2, but forgot about this PR :) Fixed now.

**Comment by Kelketek** [comment]
@e-kolpakov Update this has to the one that occurs when you merge the other PR, then ping me on it.

**Comment by e-kolpakov** [comment]
@Kelketek this PR needs to be merged before the demo as well.

**Comment by Kelketek** [comment]
:+1:

**Pull request merged**
