### PR TITLE
Update problem-builder dependency.

### PR DESCRIPTION
**Pull request by itsjeyd**
This PR pulls in changes from the following constituent PRs (newest first):

* https://github.com/open-craft/problem-builder/pull/133 (Remove migration that extends course_id column)
* https://github.com/open-craft/problem-builder/pull/132 (Implement Completion XBlock)
* https://github.com/open-craft/problem-builder/pull/130 (Extend course_id field to 255 characters)
* https://github.com/open-craft/problem-builder/pull/129 (Instructor Tool uses the Course Blocks REST API)
* https://github.com/open-craft/problem-builder/pull/128 (Uses the same import path for instructor_task.models as edxapp)
* https://github.com/open-craft/problem-builder/pull/127 (Bump version to 2.6.0)
* https://github.com/open-craft/problem-builder/pull/125 (Accessibility updates)
* https://github.com/open-craft/problem-builder/pull/124 (Handle unresolvable anonymous ids gracefully)
* https://github.com/open-craft/problem-builder/pull/122 (Remove "Message (Assessment Review)" from Problem Builder in Studio)
* https://github.com/open-craft/problem-builder/pull/123 (Update master with changes from edx-release)
* https://github.com/open-craft/problem-builder/pull/120 (Update xblock-utils to v1.0.3)

cf. [OC-2086](https://tasks.opencraft.com/browse/OC-2086)

**Reviewers**

- [ ] @mtyaka 
- [ ] @bradenmacdonald

### CODE REVIEW

**Comment by mtyaka** [comment]
@itsjeyd I think we will have to skip the changes from https://github.com/open-craft/problem-builder/pull/130. It includes a migration that is going to be removed (not reverted!) in https://github.com/open-craft/problem-builder/pull/131.

Since I am not sure when https://github.com/open-craft/problem-builder/pull/131 is getting merged, I think we should open a separate PR that only removes the migration file, and merge it to master before bumping the version number here. I'll prepare that PR now.

**Comment by itsjeyd** [comment]
@mtyaka I see, thanks for the info. Ping me when that PR is ready, I can review it.

The build for this just failed with "Action failed: bundle install", which seems unrelated to the changes introduced here. Do you know what might be causing that failure by any chance?

**Comment by mtyaka** [comment]
@itsjeyd PR is here: https://github.com/open-craft/problem-builder/issues/133

The build error indicates that bundler was not found on the VM, which is strange. Maybe it was just a random/temporary CircleCI problem. I restarted the build to see.

**Comment by itsjeyd** [comment]
@mtyaka I had a look, https://github.com/open-craft/problem-builder/pull/133 looks good to me. Let me know if there's anything I should do to test that PR manually?

**Comment by mtyaka** [comment]
@itsjeyd The Problem Builder PR is merged.

It looks like bundler is no longer installed by default on CircleCI: https://discuss.circleci.com/t/bundle-command-not-found/3783

It looks like everybody's simply been merging broken builds since August 😕 https://github.com/edx-solutions/edx-platform/pulls?q=is%3Apr+is%3Aclosed

**Comment by itsjeyd** [comment]
Rebased from de5813f15e41fb4633d2b2e1c852174fe74a8ff7 (to pull in changes from https://github.com/open-craft/problem-builder/pull/133).

**Comment by itsjeyd** [comment]
@mtyaka I updated the commit hash to point to updated master, and updated the PR description to include https://github.com/open-craft/problem-builder/pull/133.

And thanks for looking into the bundler issue. Fixing it is out of scope here, then.

**Comment by itsjeyd** [comment]
@mtyaka If you're happy with the updates, can I get a thumbs-up from you please? :)

**Comment by bradenmacdonald** [comment]
@mtyaka Yep, see https://github.com/edx-solutions/edx-platform/pull/754 . Unfortunately there are several other build issues which are still unresolved. I'm not sure who's responsible for maintaining CI builds on this fork at the moment; we might also only care about the Eucalyptus builds.

**Comment by bradenmacdonald** [comment]
:+1:

- [ ] I don't have a dogwood solutions devstack set up at the moment, so will rely on your existing testing.
- [x] I read through the code
- [ ] -I checked for accessibility issues-
- [ ] -Includes documentation-

**Comment by itsjeyd** [comment]
Thanks @mtyaka and @bradenmacdonald, merging now.

**Pull request merged**
