### PR TITLE
Deletion commits necessary for api-integration

### PR DESCRIPTION
**Pull request by viadanna**
This PR includes the commits to `edx-platform` necessary for `api-integration==2.5.11`

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @viadanna! I've created [OSPR-3220](https://openedx.atlassian.net/browse/OSPR-3220) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by viadanna** [comment]
@wajeeha-khalid @xitij2000 It seems a single commit is necessary to fix the issue related to data deletion. I've fixed the conflicts on that, so merging this branch on the release would be the only necessary step.

On the other hand, the CircleCI tests points to an error generating error reports, not sure how significant is that.

**Comment by xitij2000** [comment]
This was included in #1426

**Comment by viadanna** [comment]
Awesome, thanks!

**Pull request closed without merging**
