### PR TITLE
Third party auth: stale migrations cleanup

### PR DESCRIPTION
**Pull request by e-kolpakov**
Removed noop migrations to simplify rebases in the future (as upstream have their own 0004 and 0005)

### CODE REVIEW

**Comment by Kelketek** [comment]
:+1: , but see my notes on the ticket.

**Comment by bradenmacdonald** [comment]
:+1: But coordinate with devops before merging this. They will need to roll back prod to `0003` before deploying this change.

**Comment by e-kolpakov** [comment]
@fredsmith @feanil I'm about removing two latest migrations from TPA app; they are basically a noop (0005 reverts all changes made in 0004) and upstream edx-platform have it's own 0004 and 0005, so it would simplify the next rebase slightly (and maybe help avoid migration conflicts).

This would require running migrations once (per instance) with `delete-ghost-migrations` key, i.e. `./manage.py lms migrate third_party_auth --delete-ghost-migrations --settings=instance_settings`.

Let me know if you have any objections - there's no particular merge deadline for this, but let's target next release (after Jan 6th) with this.

**Comment by feanil** [comment]
Can you provide more detail about this?  Are these migrations that are only on the solutions fork?

**Comment by e-kolpakov** [comment]
@feanil yes, this two are on solutions only.

**Comment by bradenmacdonald** [comment]
@feanil The migration 0004 was made on the solutions fork for an SSO feature. Eventually we realized that there was a better way to implement it so we merged a revert PR that added migration 0005 which reverts 0004, and we removed the related code. So the end result is that migrations 0004+0005 together have no effect. In the mean time, the normal edx-platform has added more migrations, so there is now a conflict between the unwanted 0004/0005 migrations on edx-solutions and the useful migrations on the normal fork.

This PR deletes the unwanted noop migrations, so that we won't get a conflict in the upcoming Dogwood rebase. You can either run the migration backwards to 0003 before merging this PR, or merge it and then force a fake migration to 0003 (may be tricky).

**Comment by antoviaque** [comment]
@feanil Do you need any additional info, or can we merge this?

**Comment by feanil** [comment]
I would like @fredsmith to chime in but seems fine to me.

**Comment by antoviaque** [comment]
@feanil Thanks! 

@fredsmith What do you think?

**Comment by e-kolpakov** [comment]
@feanil @fredsmith created https://openedx.atlassian.net/browse/DEVOPS-3615 for review task.

**Comment by fredsmith** [comment]
:+1:

**Pull request merged**
