### PR TITLE
Fix hash update for Groupwork V2

### PR DESCRIPTION
**Pull request by Kelketek**
Hash was accidentally updated for problem-builder instead.

@bradenmacdonald @e-kolpakov

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
:+1:

**Comment by e-kolpakov** [comment]
:+1:

**Comment by Kelketek** [comment]
Looks like @antoviaque committed a separate fix for this this morning, so closing here.

**Comment by antoviaque** [comment]
@Kelketek Thanks, I hadn't seen this PR. Note that on the solutions fork you can update hashes directly, as long as the commits added have been reviewed on their respective repos, you don't need to open a PR for it (especially when the requirements are broken like here).

**Pull request closed without merging**
