### PR TITLE
Workaround for Step Builder Progress Issues

### PR DESCRIPTION
**Pull request by bradenmacdonald**
When a student views a Step Builder problem in Apros, if the Step Builder steps contain any HTMLModules, the HTML modules will emit `progress` events because of [this code](https://github.com/edx-solutions/edx-platform/commit/6d2c73caebc0a4f227915c7a08ddce6048f7ed55).

Since Apros doesn't see the child XBlocks, this results in discrepancies about the user's total progress. 

@ziafazal requested: "If we can change step-builder xblock in a way it would send only component id of the parent step-builder xblock at time of completion that should fix a scenario where progress returned by edx-platform API exceeds progress calculated by apros."

Unfortunately, Step Builder cannot control whether or not the HTML Module emits a progress event when it renders. However, since [this code](https://github.com/edx-solutions/edx-platform/blob/ziafazal/YONK-309/lms/djangoapps/progress/signals.py#L49-L52) checks the parent block type before processing progress events for HTML modules, we can easily configure the platform to ignore the 'progress' events coming from HTML modules inside Step Builder problems, but adding `sb-step` to `PROGRESS_DETACHED_CATEGORIES`.

Adding `sb-step` to `PROGRESS_DETACHED_CATEGORIES` implements the fix requested by Zia. The overall progress/grade event for the block is unaffected, since a normal Step Builder hierarchy is like this:
* `step-builder` - emits a `grade` event upon final completion; no `progress` or other events
    * `sb-step` - doesn't emit events
       * `html` - emits unwanted `progress` event
       * `mcq/mrq/answer`
    * `sb-step`
       * `html` - emits unwanted `progress` event
       * `mcq/mrq/answer`

Test Instructions:

1. Create a course with a Step Builder component containing two steps, with HTML modules in each step.
1. View the Step Builder unit in Apros, and interact with it.
1. Notice the progress is no longer inconsistent between the "Cohort" page and the home page.

### CODE REVIEW

**Comment by ziafazal** [comment]
LGTM 👍

**Comment by smarnach** [comment]
I've reproduced the original bug locally, and tested that it does not occur anymore with this change applied.  All working fine, :+1:.

**Comment by bradenmacdonald** [comment]
@ziafazal No, originally only Step Builder was specified as the problem here, and this approach to fixing it cannot work for Problem Builder. Since we need to support Problem Builder as well, I would suggest that we add a change to edx-platform to only increase progress when the parent block is a 'vertical' type. That would ignore all XBlock children universally.

**Comment by mattdrayer** [comment]
If we're changing the progress eventing logic such that less modules will count toward user progress do we need to consider cleaning up the entire set of recorded events to-date?

**Comment by bradenmacdonald** [comment]
Closing in favor of #677. Also moved discussion of Matt's question to that PR.

**Pull request closed without merging**
