### PR TITLE
[MCKIN-7179] Bump version of xblock-image-explorer.

### PR DESCRIPTION
**Pull request by tomaszgy**
Signed-off-by: Tomasz Gargas <tomasz@opencraft.com>

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @tomaszgy! I've created [OSPR-2389](https://openedx.atlassian.net/browse/OSPR-2389) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx-solutions/edx-platform/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by bradenmacdonald** [comment]
@tomaszgy  We should look into why the old comment said "use tag v1.1.0" but we used tag 0.9

**Comment by tomaszgy** [comment]
@bradenmacdonald Good point. I asked Afzal to have a look at it since he's done work on the xblock-image-explorer and on this ticket.

Closing this PR in favor of https://github.com/edx-solutions/edx-platform/pull/1070.

**Comment by afzaledx** [comment]
@bradenmacdonald @tomaszgy , I saw that the last change was reverted, so I was wondering if I changed the version it would be confusing. I guess someone mentioned the correct versions here.

**Pull request closed without merging**
