### PR TITLE
Bump edx-completion to 0.1.10.1

### PR DESCRIPTION
**Pull request by viadanna**
This PR bumps completions to add OAuth authentication to POST endpoint.

**Testing instructions**:

1. Create an OAuth token to test the POST endpoint.
2. Perform a POST request to set completion, i.e.
```
curl -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' -d '{"username":"<username>","course_key":"<course_key>","blocks":{"<block_id>":1.0}}' localhost:8000/api/completion/v1/completion-batch
```

**Reviewers**
- [x] @jcdyer 
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @viadanna! I've created [OSPR-3022](https://openedx.atlassian.net/browse/OSPR-3022) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by jcdyer** [comment]
:+1:  Works for me on this branch.

**Comment by viadanna** [comment]
@jcdyer I think you just commented instead of approving so I can merge :)

**Comment by jcdyer** [comment]
Sorry about that. :(

**Pull request merged**
