### PR TITLE
Implement cached calculation of means.

### PR DESCRIPTION
**Pull request by jcdyer**
Performance of completion v0 api requests is poor when requesting the mean completion ratio for numerous courses, because each one has to be calculated separately.  This ticket caches the results of that calculation, so that it doesn't slow down the QA team, who regularly deals with queries across a large number of courses.

### JIRA tickets

MCKIN-6669, OC-3575

### Discussions

See tickets.

### Dependencies

None

### Screenshots

N/A

### Sandbox URL

Upon request

### Merge deadline

ASAP, as this is causing site usability issues for McKinsey QA

### Testing instructions

1. Enroll the `staff` user in several courses (10-20)
2. While logged in as `staff`, visit https://localhost:8000/api/completion/v0/course/?page_size=30&username=staff&requested_fields=mean.
3. Verify that the request does not take mutiple times as long as the same request without requested_fields=mean.

### Reviewers

- [ ] @bradenmacdonald 

### Settings

None

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @jcdyer! I've created [OSPR-2067](https://openedx.atlassian.net/browse/OSPR-2067) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by jcdyer** [comment]
Aren't tests supposed to run here?  I'm not seeing anything.

**Comment by bradenmacdonald** [comment]
@jcdyer Tests only run if you push the commit to the `edx-solutions` fork. I've done that for you now. If this is a hassle, I can try to get you push access - let me know.

**Comment by jcdyer** [comment]
There's a little purple blob on the top left of the circle ci page that says that the tests aren't running. https://circleci.com/gh/edx-solutions/edx-platform/1958?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

It's been "running" (not running) for 2h 20m.

**Comment by jcdyer** [comment]
But if I click on "Previous build" from there, it says it *is* running, and has been for 55 minutes.  I think there's probably nothing to worry about here. https://circleci.com/gh/edx-solutions/edx-platform/1957#config/containers/0

**Comment by jcdyer** [comment]
@bradenmacdonald This needs a review and another push to edx-solutions to get tests running.  The only failures on the last build above are quality failures, and I've confirmed that they have been resolved locally.

**Comment by bradenmacdonald** [comment]
Ok, cool.

And yeah I'm on a Mac but I use the vagrant devstack so everything's running on an Ubuntu VM and should behave the same way for me as you, no?

**Comment by jcdyer** [comment]
Ready for another review and a push to CI.

**Pull request merged**
