### PR TITLE
MCKIN-9024 & BB-701: Update completion aggregator version WIP

### PR DESCRIPTION
**Pull request by giovannicimolin**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @giovannicimolin! I've created [OSPR-2922](https://openedx.atlassian.net/browse/OSPR-2922) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by Agrendalath** [comment]
This will be bumped in edx-solutions/edx-platform#1333 to trigger the CI.

**Comment by Agrendalath** [comment]
@giovannicimolin, we can merge this as the CI was triggered in edx-solutions/edx-platform#1333.

**Comment by Agrendalath** [comment]
All right, as the other PR is approved, we can close this again.

**Pull request closed without merging**
