### PR TITLE
MCKIN-15673 Problem builder version bump

### PR DESCRIPTION
**Pull request by musmanmalik**
Problem builder version bump

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @musmanmalik! I've created [OSPR-4390](https://openedx.atlassian.net/browse/OSPR-4390) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by wajeeha-khalid** [comment]
@musmanmalik we should check what is in .14 version? merging .15 version before .14 will bring in all changes from that version too and can break things on stage/prod.

**Comment by wajeeha-khalid** [comment]
@moeez96 @musmanmalik IMO this should not have been merged; there seems to be a skip of one version; we are changing from .13 to .15 directly

**Comment by moeez96** [comment]
@wajeeha-khalid .14 is already taken. Please have a look
https://github.com/open-craft/problem-builder/releases

Yes the changes in .14 will be brought in along.

**Comment by nasirhjafri** [comment]
So .14 is a minor fix by someone from edx team. It should be safe to move to .15
https://github.com/open-craft/problem-builder/pull/269/

**Comment by moeez96** [comment]
Supposing .14 is a major fix (for future), I do not think can we work around jumping directly to .15; please correct me.

**Comment by wajeeha-khalid** [comment]
Thank you @moeez96 and @nasirhjafri for confirming
It would be a good idea to mention such version changes in PR description too and also highlight to QA team to additionally test those changes as well (in this case changes from .14)

I am not sure how safe would it be if we have a skipped version bump in this repo and we take a higher version to stage/prod without the knowledge and testing for the changes of skipped version.

Happy to hear how we can improve this process.
cc: @musmanmalik

**Comment by wajeeha-khalid** [comment]
@moeez96 That is correct; please see my above comment; I have the same concern.

> Supposing .14 is a major fix (for future), I do not think can we work around jumping directly to .15; please correct me.

**Pull request merged**
