### PR TITLE
(YONK-217) - Duplicate signal prevention

### PR DESCRIPTION
**Pull request by marjev**
@Kelketek, could you please take a look at this PR?

I believe you changed urls.py at some point, but your change left a pair of identical url regexes. I removed duplicates, but please confirm they are not needed.

Other two changes will prevent duplicate receiving of the same signal. If I'm not mistaken, you mentioned that there were some issues with duplicate signals, so perhaps that caused the YONK-217 issue. I couldn't get conclusive information since tracking log on apros side is not available for internal developers.

Also, can you suggest someone to be the 2nd reviewer here, since this is something under the Cypress Rebase epic on JIRA.

### CODE REVIEW

**Comment by antoviaque** [comment]
@marjev Currently @Kelketek is on holidays (last week & this week), so I'm afraid he won't be able to review. We could still provide one of the two reviewers - maybe @mattdrayer would be a good second reviewer?

**Comment by marjev** [comment]
@antoviaque, I would be grateful if someone from your team would take a look at the changes.

**Comment by antoviaque** [comment]
@marjev Yup, that's what I was proposing for the first reviewer - I was mentioning @mattdrayer as the second reviewer since it's API and gradebook related.

**Comment by mattdrayer** [comment]
@marjev -- can you explain the misbehavior a little more clearly here?  Was the GRADES_UPDATED signal being picked up by the gradebook score_changed receiver?  This seems odd to me, if true.

**Comment by mattdrayer** [comment]
Ah, I think I see now -- the gradebook was performing the grading workflow, and THIS was resulting in a duplicate downstream signal which was confusing the 'credit' receiver -- is that correct?

**Comment by marjev** [comment]
@mattdrayer, that's correct. 

Signal score_changed was problematic in tests. 

The other signal, grades_updated, was once duplicated on prod. It's not occurring all of the time, but in case it happens again, this will prevent duplicate calculations.

**Comment by mattdrayer** [comment]
SGTM -- thanks for the clarification -- :+1:

**Comment by marjev** [comment]
@chrisndodge could you please take a look at this PR?

**Comment by smarnach** [comment]
@marjev Just to let you know, I'm taking a look at this now (filling in for Jonathan, who is on vacation).

**Comment by smarnach** [comment]
Looks good to me, :+1:.  I can't tell whether this actually caused YONK-217, but I'm confident that these changes can't possibly break anything.  Django matches URL patterns in order, so the second occurrence can't ever be matched.  Adding a `dispatch_uid` to a signal receiver can't hurt either, since we never want the same receiver to be called twice for the same signal.

**Comment by marjev** [comment]
@smarnach thanks for the review!

I just cleaned the URL patterns since there were duplicates. I know it's impossible for that one to be the cause of the issue, but since I saw it, I decided to remove the extra ones to increase readability, if nothing more.

Jonathan actually suggested to me to take a look at signals since he had issues with them during the rebasing process due to some tests failing. That's the only hint I had. This issue only occurred once and I wasn't able to reproduce it on any of the servers or locally, and it was logged on NewRelic only once on a day the deployment was done.

**Pull request merged**
