### PR TITLE
YONK-348: move edx_solutions_api_integration to seperate repo

### PR DESCRIPTION
**Pull request by msaqib52**
As a part of consolidation work we are moving ``edx_solutions_api_integration`` app to separate repo and installing it via git in edx-platform. Here is the newly created repo for [edx_solutions_api_integration](https://github.com/edx-solutions/api-integration) app.

@ziafazal would please review?

### CODE REVIEW

**Comment by ziafazal** [comment]
👍

**Comment by bradenmacdonald** [comment]
@ziafazal @msaqib52 When I try to update my solutions devstack with this change, it gives me this error:

```
CommandError: One or more models did not validate:
edx_solutions_api_integration.grouprelationship: Accessor for field 'group' clashes with related field 'Group.grouprelationship'. Add a related_name argument to the definition for 'group'.
edx_solutions_api_integration.grouprelationship: Reverse query name for field 'group' clashes with related field 'Group.grouprelationship'. Add a related_name argument to the definition for 'group'.
edx_solutions_api_integration.coursegrouprelationship: Accessor for field 'group' clashes with related field 'Group.coursegrouprelationship_set'. Add a related_name argument to the definition for 'group'.
edx_solutions_api_integration.groupprofile: Accessor for field 'group' clashes with related field 'Group.groupprofile'. Add a related_name argument to the definition for 'group'.
edx_solutions_api_integration.groupprofile: Reverse query name for field 'group' clashes with related field 'Group.groupprofile'. Add a related_name argument to the definition for 'group'.
```

Is that a known issue? Also, are there upgrade instructions somewhere for the management commands and anything else that needs to be run when updating a solutions devstack to these external projects?

**Comment by ziafazal** [comment]
@bradenmacdonald I think removing *.pyc files should fix this issue.

**Comment by bradenmacdonald** [comment]
@ziafazal You're right. I was sure I had already tried that, but apparently not. Thanks!

**Pull request merged**
