### PR TITLE
[MCKIN-8890] Bump completion version.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Fixes an issue with the API making 1 query per user because of a missing select_related call.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @UmanShahzad! I've created [OSPR-2804](https://openedx.atlassian.net/browse/OSPR-2804) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by UmanShahzad** [comment]
Oh gosh, it's been an hour this has been in the _queue_!

**Comment by jcdyer** [comment]
It must be stuck behind my PR.  But yours was opened first, so I don't know.  Circle CI is a mysterious vortex of pain.

**Comment by UmanShahzad** [comment]
That's crazy...

**Comment by jcdyer** [comment]
You got hit by another ticking clock flakebomb.  AssertionError: '2018-11-15T16:20:13Z' != '2018-11-15T16:20:12Z'

**Pull request merged**
