### PR TITLE
Updating master with release-candidate

### PR DESCRIPTION
**Pull request by ihtram**

### CODE REVIEW

**Comment by ihtram** [comment]
@nasirhjafri Please take a look and verify all these commits are deployed on production.

**Comment by nasirhjafri** [comment]
@ihtram One commit is still pending for prod and will be deployed today. Please merge after prod deployment.

**Comment by ihtram** [comment]
@nasirhjafri sure. We can wait for next prod deployment but please do not merge anything into release-candidate before updating master branch. It would be great if we can follow this for all upcoming prod releases.

**Comment by ihtram** [comment]
@nasirhjafri any updates? are all of these commits on prod or not?

**Comment by moeez96** [comment]
@ihtram All of these commits are on prod.

**Pull request merged**
