### PR TITLE
[MCKIN-8714] Bump api-integration

### PR DESCRIPTION
**Pull request by Agrendalath**
This is a version bump for https://github.com/edx-solutions/api-integration/pull/162.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Agrendalath! I've created [OSPR-2768](https://openedx.atlassian.net/browse/OSPR-2768) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by UmanShahzad** [comment]
@zamanafzal Why did you close this? Also, what happened to the [development branch](https://github.com/edx-solutions/edx-platform/tree/development)?

**Comment by zamanafzal** [comment]
@UmanShahzad  I think I mistakenly hit the close button. Can you open this PR again, please.

**Comment by UmanShahzad** [comment]
@zamanafzal No worries. I think the development branch is also gone though, and you seemed to have automatically closed other PRs targeting that branch.

Let us know if you accidentally deleted the development branch somehow. We should be able to restore it pretty easily.

**Comment by zamanafzal** [comment]
@UmanShahzad I am not sure about that. I didn't delete the development branch. If this happens somehow then please restore that. Thanks.

**Pull request merged**
