### PR TITLE
Make user API use the same regex as everyone else.

### PR DESCRIPTION
**Pull request by Kelketek**
@bradenmacdonald @antoviaque 

Low-priority PR that should only affect dev environments, which may have split courses, etc, which won't fit the old regex pattern. Xavier, we'll need a second reviewer for this.

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
:+1:

**Comment by antoviaque** [comment]
This LGTM, but I know @ziafazal did some work on testing the fork with birch and converting some of the API calls format, so I'll let him confirm. Also CC'ing @mattdrayer FYI.

Also, are there tests for these calls?

**Comment by ziafazal** [comment]
:+1:

**Comment by Kelketek** [comment]
@antoviaque All the tests work by simulated client accessing URLs, so yes. I've run them again to verify.

**Pull request merged**
