### PR TITLE
Add version bump for eoc-journal and virtualreality.

### PR DESCRIPTION
**Pull request by xirdneh**
Add new versions for eoc-journal and virtualreality xblocks.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @xirdneh! I've created [OSPR-3742](https://openedx.atlassian.net/browse/OSPR-3742) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@xirdneh Do you need edX review for this?

**Comment by xirdneh** [comment]
@natabene  Not sure, @viadanna Do we need a review from edx?

**Comment by viadanna** [comment]
@natabene @xirdneh I don't think so, this just bumps the two XBlocks that have i18n implemented in the latest version.

**Pull request merged**
