### PR TITLE
Make a change to trigger a build (WIP)

### PR DESCRIPTION
**Pull request by jcdyer**
@bradenmacdonald @macornwell:

Both the mobile-only PR (#1009) and @tomaszgy's fixes to DRF have been merged to master, so here's a new branch to make sure we get a green build with all that together.

For anyone finding this through the OSPR, this branch exists only to get a CI build running, and will not be merged.

I had accidentally merged #1009 without triggering a build on its final commits.  When I finally did run CI on it, I got a failure, for a broken dependency that has been resolved in the meantime.  This branch contains the untested code, and the fix for the unrelated problem.  If the build fails, we will address the breakage in a new, clean PR.  Once we have a result either way, this PR and branch will be deleted.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @jcdyer! I've created [OSPR-2224](https://openedx.atlassian.net/browse/OSPR-2224) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by bradenmacdonald** [comment]
@jcdyer @tomaszgy @macornwell Hmm, looks like we still have some issues :/

**Comment by tomaszgy** [comment]
@bradenmacdonald Could we run `Rebuild without cache` on CI to make sure it doesn't use some old cached packages?

**Comment by bradenmacdonald** [comment]
@tomaszgy  Sure, done. But it didn't seem to help on some other PRs.

**Comment by tomaszgy** [comment]
@bradenmacdonald Thanks. I see it failed again which is just very weird. How come https://github.com/edx-solutions/edx-platform/pull/1008 passed? Might be worth `ssh`-ing into CI build VM and checking the source code of DRF package to make sure it contains the patches from `https://github.com/open-craft/django-rest-framework/tree/tomaszgy/lazy_strings_included` (last two commits on this branch).

**Comment by jcdyer** [comment]
In the pip install output I'm seeing this:

Requirement already satisfied: djangorestframework==3.2.3 from git+https://github.com/open-craft/django-rest-framework.git@tomaszgy/lazy_strings_included#egg=djangorestframework==3.2.3 in /home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages (from -r requirements/edx/base.txt (line 40))

So even with caching disabled, it's happy with the version it has.  I think a good solution here would be to bump the egg version:

    git+https://github.com/open-craft/django-rest-framework.git@tomaszgy/lazy_strings_included#egg=djangorestframework==3.2.3

Revise this to 

    git+https://github.com/open-craft/django-rest-framework.git@tomaszgy/lazy_strings_included#egg=djangorestframework==3.2.3.opencraft1

and I think the caching problem will go away.  I'll push a commit to test it out.

**Comment by bradenmacdonald** [comment]
@tomaszgy  @jcdyer  This issue should be fixed now with https://github.com/edx-solutions/edx-platform/pull/1022

**Comment by jcdyer** [comment]
:+1:

**Pull request closed without merging**
