### PR TITLE
MCKIN-6708 Bump End of Course Journal Xblock's version.

### PR DESCRIPTION
**Pull request by tomaszgy**
## MCKIN-6708
This PR bumps the version of the End of the Course Journal Xblock to include fixes from https://github.com/open-craft/xblock-eoc-journal/pull/10 as a part of MCKIN-6708.

Signed-off-by: Tomasz Gargas <tomasz@opencraft.com>

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @tomaszgy! I've created [OSPR-2166](https://openedx.atlassian.net/browse/OSPR-2166) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx-solutions/edx-platform/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by tomaszgy** [comment]
@jcdyer, I don't quite understand how this change causes so many tests fail. Would you have any idea?

**Comment by jcdyer** [comment]
Taking a look now.

**Comment by jcdyer** [comment]
I don't really get it either.  The stack trace doesn't touch on the eoc_journal code at all.  If I trace it out, it looks like the error runs straight into this django-rest-framework issue: https://github.com/encode/django-rest-framework/issues/3354.  But that's [triggered by this line](https://github.com/edx/edx-val/blame/eee4c2f0749e229f87a86d853d6a8957b6fc929d/edxval/serializers.py#L27) which hasn't been changed in 2 years.

**Comment by jcdyer** [comment]
Probably the easiest solution would be to upgrade DRF to something that has that patch included.

But oddly, the same version of DRF was present on CircleCI#2012, which was the last successful build, so there's some odd interaction between DRF and something else.  So I copied the results of `pip freeze` from that and from the first failing build (CircleCI#2016), and here's what's changed between the two versions.

**Comment by jcdyer** [comment]
```
--- good        2018-01-26 14:24:52.329694169 -0500
+++ bad 2018-01-26 14:32:30.312293642 -0500
@@ -5 +5 @@
-api-integration==1.6.5
+api-integration==1.6.6
@@ -9 +9 @@
-attrs==17.2.0
+attrs==17.4.0
@@ -20,2 +20,2 @@
--e git+git@github.com:edx-solutions/edx-platform.git@663984511bf82c8118ed6595ddda82307246ee3f#egg=calc&subdirectory=common/lib/calc
--e git+git@github.com:edx-solutions/edx-platform.git@663984511bf82c8118ed6595ddda82307246ee3f#egg=capa&subdirectory=common/lib/capa
+-e git+git@github.com:edx-solutions/edx-platform.git@4dd192ad14fd65833a144df93f94d00f4e75fa7d#egg=calc&subdirectory=common/lib/calc
+-e git+git@github.com:edx-solutions/edx-platform.git@4dd192ad14fd65833a144df93f94d00f4e75fa7d#egg=capa&subdirectory=common/lib/capa
@@ -23 +23 @@
-cffi==1.11.2
+cffi==1.11.4
@@ -26 +26 @@
--e git+git@github.com:edx-solutions/edx-platform.git@663984511bf82c8118ed6595ddda82307246ee3f#egg=chem&subdirectory=common/lib/chem
+-e git+git@github.com:edx-solutions/edx-platform.git@4dd192ad14fd65833a144df93f94d00f4e75fa7d#egg=chem&subdirectory=common/lib/chem
@@ -32 +32 @@
-course-edx-platform-extensions==1.0.6
+course-edx-platform-extensions==1.0.7
@@ -42 +42 @@
-decorator==4.1.2
+decorator==4.2.1
@@ -46 +46 @@
-discussion-edx-platform-extensions==1.1.7
+discussion-edx-platform-extensions==1.1.9
@@ -50 +50 @@
-django-babel==0.6.1
+django-babel==0.6.2
@@ -52 +52 @@
-django-braces==1.11.0
+django-braces==1.12.0
@@ -64,0 +65 @@
+django-js-asset==1.0.0
@@ -95 +96 @@
--e git+git@github.com:edx-solutions/edx-platform.git@663984511bf82c8118ed6595ddda82307246ee3f#egg=dogstats_wrapper&subdirectory=common/lib/dogstats
+-e git+git@github.com:edx-solutions/edx-platform.git@4dd192ad14fd65833a144df93f94d00f4e75fa7d#egg=dogstats_wrapper&subdirectory=common/lib/dogstats
@@ -136,2 +137,2 @@
-futures==3.1.1
-fuzzywuzzy==0.15.1
+futures==3.2.0
+fuzzywuzzy==0.16.0
@@ -151,2 +152,2 @@
-ipaddress==1.0.18
-isodate==0.5.4
+ipaddress==1.0.19
+isodate==0.6.0
@@ -154 +155 @@
-Jinja2==2.9.6
+Jinja2==2.10
@@ -196 +197 @@
--e git+git@github.com:edx-solutions/edx-platform.git@663984511bf82c8118ed6595ddda82307246ee3f#egg=Open_edX
+-e git+git@github.com:edx-solutions/edx-platform.git@4dd192ad14fd65833a144df93f94d00f4e75fa7d#egg=Open_edX
@@ -203 +204 @@
-parsel==1.2.0
+parsel==1.3.1
@@ -217,2 +218,2 @@
-pyasn1==0.3.7
-pyasn1-modules==0.1.4
+pyasn1==0.4.2
+pyasn1-modules==0.2.1
@@ -234 +235 @@
-pyOpenSSL==17.3.0
+pyOpenSSL==17.5.0
@@ -237 +237,0 @@
-pysqlite==2.8.3
@@ -241 +241 @@
-python-magic==0.4.13
+python-magic==0.4.15
@@ -260 +260 @@
--e git+git@github.com:edx-solutions/edx-platform.git@663984511bf82c8118ed6595ddda82307246ee3f#egg=safe_lxml&subdirectory=common/lib/safe_lxml
+-e git+git@github.com:edx-solutions/edx-platform.git@4dd192ad14fd65833a144df93f94d00f4e75fa7d#egg=safe_lxml&subdirectory=common/lib/safe_lxml
@@ -262 +262 @@
--e git+git@github.com:edx-solutions/edx-platform.git@663984511bf82c8118ed6595ddda82307246ee3f#egg=sandbox_packages&subdirectory=common/lib/sandbox-packages
+-e git+git@github.com:edx-solutions/edx-platform.git@4dd192ad14fd65833a144df93f94d00f4e75fa7d#egg=sandbox_packages&subdirectory=common/lib/sandbox-packages
@@ -265 +265 @@
--e git+https://github.com/mckinseyacademy/xblock-scorm.git@500eb8b588e731b811d820993a349e676e27e47a#egg=scormxblock_xblock
+-e git+https://github.com/mckinseyacademy/xblock-scorm.git@8fc19744795da56200a4cf5129bfa64c9cc7332b#egg=scormxblock_xblock
@@ -271 +271 @@
-simplejson==3.11.1
+simplejson==3.13.2
@@ -284 +284 @@
--e git+git@github.com:edx-solutions/edx-platform.git@663984511bf82c8118ed6595ddda82307246ee3f#egg=symmath&subdirectory=common/lib/symmath
+-e git+git@github.com:edx-solutions/edx-platform.git@4dd192ad14fd65833a144df93f94d00f4e75fa7d#egg=symmath&subdirectory=common/lib/symmath
@@ -297 +297 @@
-w3lib==1.18.0
+w3lib==1.19.0
@@ -301,2 +301,2 @@
-WebOb==1.7.3
-Werkzeug==0.12.2
+WebOb==1.7.4
+Werkzeug==0.14.1
@@ -307,2 +307,2 @@
--e git+git@github.com:edx-solutions/edx-platform.git@663984511bf82c8118ed6595ddda82307246ee3f#egg=xblock_discussion&subdirectory=openedx/core/lib/xblock_builtin/xblock_discussion
--e git+git@github.com:edx-solutions/edx-platform.git@663984511bf82c8118ed6595ddda82307246ee3f#egg=xblock_discussion_course&subdirectory=openedx/core/lib/xblock_builtin/xblock_discussion_course
+-e git+git@github.com:edx-solutions/edx-platform.git@4dd192ad14fd65833a144df93f94d00f4e75fa7d#egg=xblock_discussion&subdirectory=openedx/core/lib/xblock_builtin/xblock_discussion
+-e git+git@github.com:edx-solutions/edx-platform.git@4dd192ad14fd65833a144df93f94d00f4e75fa7d#egg=xblock_discussion_course&subdirectory=openedx/core/lib/xblock_builtin/xblock_discussion_course
@@ -319 +319 @@
--e git+https://github.com/edx-solutions/xblock-ooyala.git@33937e77e838508a6ddc4e90c4541d92cfd25775#egg=xblock_ooyala_player
+-e git+https://github.com/edx-solutions/xblock-ooyala.git@5c64da2c4ce5b0540cd5c8702e026c05274ad48d#egg=xblock_ooyala_player
@@ -325 +325 @@
--e git+git@github.com:edx-solutions/edx-platform.git@663984511bf82c8118ed6595ddda82307246ee3f#egg=XModule&subdirectory=common/lib/xmodule
+-e git+git@github.com:edx-solutions/edx-platform.git@4dd192ad14fd65833a144df93f94d00f4e75fa7d#egg=XModule&subdirectory=common/lib/xmodule
```

**Comment by jcdyer** [comment]
I don't see anything related to django-rest-framework or django proper, but django-babel is related to translations, and that got bumped from 0.6.1 to 0.6.2, so you could look into the changelogs of that project, and try pinning it to v0.6.1 to see if that resolves the problem.  But pushing an upgrade is generally better than holding back another upgrade, since that introduces technical debt that will need to be undone later, so see if upgrading DRF breaks anything first.

**Comment by tomaszgy** [comment]
@jcdyer The tests pass now - it required pinning DRF version to a special branch of our DRF's fork where I cherry-picked the commits with patches to https://github.com/encode/django-rest-framework/issues/3354. I needed also to update few tests as the error-messaging seems to have changed in DRF.

Please let me know if it's good to go and ready for merge.

**Pull request merged**
