### PR TITLE
YONK-1173: Update xblock version to match aggregator's requirements

### PR DESCRIPTION
**Pull request by jcdyer**
Hotfix to update required XBlock, because the new completion_aggregator depends on it to run aggregator service.

Fixes YONK-1173.

## Notes

* XBlock diff from currently installed version: https://github.com/edx/XBlock/compare/xblock-1.2.0...xblock-1.2.2?expand=1
* This change is already applied on QA, so no update needs to happen there.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @jcdyer! I've created [OSPR-2702](https://openedx.atlassian.net/browse/OSPR-2702) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by jcdyer** [comment]
Testing uncovered a backwards-incompatible change in a patch release of XBlock.  I've fixed the broken test, squashed commits, and am re-running tests.

**Comment by jcdyer** [comment]
Tests failed again, with a seemingly spurious ConnectionError (via requests, via slumber) in an unrelated part of the code.  I've restarted tests again.  Hopefully it will be ready to merge in the morning.

**Comment by jcdyer** [comment]
Oh that's frustrating.  Another unrelated spurious error.  

```
ERROR: test_video_with_subs_and_transcript_index_dictionary (xmodule.tests.test_video.VideoDescriptorIndexingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/edx-platform/common/lib/xmodule/xmodule/tests/test_video.py", line 928, in test_video_with_subs_and_transcript_index_dictionary
    download_youtube_subs('OEoXaMPEzfM', descriptor, settings)
  File "/home/circleci/edx-platform/common/lib/xmodule/xmodule/video_module/transcripts_utils.py", line 187, in download_youtube_subs
    subs = get_transcripts_from_youtube(youtube_id, settings, i18n)
  File "/home/circleci/edx-platform/common/lib/xmodule/xmodule/video_module/transcripts_utils.py", line 148, in get_transcripts_from_youtube
    raise GetTranscriptsFromYouTubeException(msg)
GetTranscriptsFromYouTubeException: Can't receive transcripts from Youtube for OEoXaMPEzfM. Status code: 404.
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): video.google.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /timedtext?type=list&v=OEoXaMPEzfM HTTP/1.1" 404 1598
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): video.google.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /timedtext?lang=en&v=OEoXaMPEzfM HTTP/1.1" 404 1596
--------------------- >> end captured logging << ---------------------
```

**Pull request merged**
