### PR TITLE
Update: Adding diagnostic_feedback to Optional Apps

### PR DESCRIPTION
**Pull request by jareerahsan**

### CODE REVIEW

**Comment by antoviaque** [comment]
@jareerahsan You need to have this type of PRs reviewed before merging them. Can you still get the 2 +1s on this?

**Comment by jareerahsan** [comment]
Oh can you do one? I'll ask someone in the edx team here to do the other one.

**Comment by jareerahsan** [comment]
Sorry I forgot to tag you, @antoviaque ?

**Comment by jareerahsan** [comment]
@zvishal Can you help me find a reviewer here? Thanks!!

**Comment by zvishal** [comment]
@smagoun See Xavier and Jareers note: we need a +1 from a reviewer from edX to get this merged. Can someone take a look?

**Comment by ziafazal** [comment]
LGTM :+1:

**Pull request merged**
