### PR TITLE
Discussion bug fixes and improvements

### PR DESCRIPTION
**Pull request by e-kolpakov**
* Fixes bug with showing response vote count twice - cherry-picked upstream commit
* Added ability to set custom css classes on search messages

### CODE REVIEW

**Comment by antoviaque** [comment]
@e-kolpakov Thanks for the test btw, it's good to have it. LGTM :+1:

Once you have got the 2nd :+1: and it's merged, can you also forward-port this to the upstream discussion XBlock PR, to take care of it progressively and not add to the debt on that PR? Thanks!

**Comment by e-kolpakov** [comment]
@antoviaque Sure, that was the plan - add it to upstream PR when it got enough thumbs up to be merged.

**Comment by antoviaque** [comment]
@e-kolpakov Perfect - thanks!

**Comment by Kelketek** [comment]
:+1:

**Pull request merged**
