### PR TITLE
[MCKIN-7023] Improve XBlock i18n by allowing template translations

### PR DESCRIPTION
**Pull request by pomegranited**
Uses temporary branches for XBlock, xblock-utils, and DnDv2-new to provide fixes for XBlock template translations.

**JIRA tickets**: [MCKIN-7023](https://edx-wiki.atlassian.net/browse/MCKIN-7023)

**Discussions**: [WL-230](https://openedx.atlassian.net/browse/WL-230), [YONK-879](https://openedx.atlassian.net/browse/YONK-879?focusedCommentId=307771&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-307771)

**Dependencies**:

* https://github.com/edx/xblock-utils/pull/48
* https://github.com/edx-solutions/xblock-image-explorer/pull/37
* https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/154
* https://github.com/open-craft/xblock-drag-and-drop-v2/pull/25

**Screenshots**: See https://github.com/edx-solutions/xblock-image-explorer/pull/37 and https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/154 for before and after screenshots using dummy translations.

**Merge deadline**: ASAP

**Testing instructions**:

See https://github.com/edx-solutions/xblock-image-explorer/pull/37 for test instructions.

**Author notes and concerns**:

1. When the dependent PRs merge, we'll submit a follow-up PR to use the newly tagged versions of the dependent libraries.

**Reviewers**
- [x] @mtyaka

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-2292](https://openedx.atlassian.net/browse/OSPR-2292) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by nedbat** [comment]
@pomegranited Am I right in thinking that any PR with "[MCKIN]" in the title isn't an OSPR?

**Comment by pomegranited** [comment]
@nedbat  Yep totally -- though some people might omit the `[]`, so if you're updating the OSPR trigger, then maybe just look for `MCKIN-`?

**Comment by nedbat** [comment]
Just manual for now.. :)

**Comment by bradenmacdonald** [comment]
@nedbat @pomegranited It's a little more complicated than that. If we submit work like this upstream to `edx/edx-platform` or `edx/XBlock`, then it would need an OSPR, even though it might have a MCKIN ticket associated with it. (Because edX is not paying us for this work.)

In general, OSPRs are never used for this repository/organization though, so a good rule of thumb is to not expect OSPRs for anything in the `edx-solutions` organization, with the only exception I know of being https://github.com/edx-solutions/xblock-drag-and-drop-v2 (which should really be moved to the `edx` org now anyways) and on that one I usually just ping Sandy Student for a review directly, since he's faster than the OSPR process :-p

**Comment by bradenmacdonald** [comment]
@pomegranited  Note that in preparation for a Ginkgo rebase, this shouldn't be merged this week and we may need to target the `integration` branch instead of master. I'll send details tomorrow.

**Comment by pomegranited** [comment]
Thanks @bradenmacdonald  -- any more info about where I should be targeting with this PR?

**Comment by bradenmacdonald** [comment]
Perfect, thanks @pomegranited !

**Comment by bradenmacdonald** [comment]
Note that we need to get a green CI build before merging.

**Comment by mtyaka** [comment]
Rebased on top of 'integration' from 291fa53e8b0f465cfc976903498b79bf9fbb4a59.

**Comment by mtyaka** [comment]
Removed 291fa53e8b0f465cfc976903498b79bf9fbb4a59 to see if it has any effect on tests which are still failing.

**Comment by pomegranited** [comment]
@mtyaka Ok, the only remaining issues are quality failures, which don't seem to be related to this ticket.  What should I do?

**Comment by bradenmacdonald** [comment]
@pomegranited It's fine to ignore unrelated quality issues; another team is working on those things as part of the overall ginkgo upgrade. See https://github.com/edx-solutions/edx-platform/pull/1040#issuecomment-376156857

**Comment by bradenmacdonald** [comment]
@pomegranited Probably, to make the team that's doing the rebase have an easier time, with fewer commits to deal with.

**Comment by pomegranited** [comment]
@bradenmacdonald  done.

**Comment by mtyaka** [comment]
:+1:

- [x] I tested this: I installed this branch on the solutions devstack and verified both versions of DnDv2 still work correctly.
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ n/a
- [ ] ~~Includes documentation~~ n/a

**Pull request merged**
