### PR TITLE
YONK-1752 - Added composite index on (module_id, grade, student_id) columns to eliminate full table scans

### PR DESCRIPTION
**Pull request by shafqatfarhan**
A Database index against the module_id column of courseware_studentmodule table was removed in ironwood. This table is extensively called during report generation and has more than 40 million records on prod. So, it resulted in slow query response time in task calculate_problem_responses_csv to fetch reports. 

Adding a composite index on (module_id, grade, student_id) would eliminate the full table scan.

### CODE REVIEW

**Comment by shafqatfarhan** [comment]
@ormsbee @georgebabey Please review this PR. Added back the index on `module_id` column for `SudentModule` model

**Comment by ormsbee** [comment]
FYI to the folks who were in the earlier discussion: @feanil, @coryleeio, @adzuci

**Comment by ormsbee** [comment]
Oh wait, this is being done only on the fork? I thought this was being pulled upstream into edx-platform. :(

**Comment by natabene** [comment]
@ormsbee We need to first solve this for Yonkers instance, as there is a dire business need on prod. @feanil Do you think we need this in Juniper and master?

**Comment by ormsbee** [comment]
@natabene: I had originally thought this was a PR to merge upstream. If you need to merge this onto the solutions fork to resolve a production incident and are okay with a bit of downtime (on the order of minutes) as it rolls out, please do so. We can sort out the bodies later w.r.t. to upstreaming.

**Comment by natabene** [comment]
@shafqatfarhan After talking to Dave, please change the migration name and commit message as expected before you merge this to solutions fork. You don't need to do the rest (figuring out stuff), unless you will upstream it.

**Comment by shafqatfarhan** [comment]
@ormsbee I have updated the migration file name and also made the commit message more descriptive. PR is ready for review again. Thanks

**Comment by georgebabey** [comment]
We discovered there is actually a composite index on edx.org that was being used which is why their reports were not impacted. @shafqatfarhan can we update this ticket to match the existing edx.org index, that will make it easier to push this upstream since that index already exists.

Table: courseware_studentmodule
Index Name: courseware_stats
Columns: module_id,grade,student_id

**Comment by shafqatfarhan** [comment]
@georgebabey @ormsbee Thank you for the discovery. I have added the composite index `courseware_stats ` on columns ` module_id, grade, student_id`.

PR is ready for review. Thanks

**Pull request merged**
