### PR TITLE
Fix issue where unicode encodings caused XBlock rendering to fail.

### PR DESCRIPTION
**Pull request by Kelketek**
md5 does not accept Unicode objects, only raw strings. This ensures a raw string is always used in a straightforward way for this purpose, and mirrors the upstream change for the same fix.

### CODE REVIEW

**Comment by mtyaka** [comment]
Should this be added to https://github.com/edx/edx-platform/pull/2968 ?

**Comment by antoviaque** [comment]
@mtyaka Yes, this should be added to that PR 

@Kelketek It's missing a unit test - can you add it, and recreate this PR against the branch from https://github.com/edx/edx-platform/pull/2968 ?

**Comment by Kelketek** [comment]
@mtyaka @antoviaque This changed was backported from upstream. There is no need to add it to that PR.

**Comment by mtyaka** [comment]
@Kelketek There may have been a similar change upstream in a different part of the codebase - the particular line your patch changes is currently not present upstream AFAICT, it's https://github.com/edx/edx-platform/pull/2968 that adds it.

**Comment by Kelketek** [comment]
@mtyaka Ah, you're right. The change *is* in a different part of the codebase. I'll get started on that PR, then.

**Comment by Kelketek** [comment]
@mtyaka @antoviaque The requested PR is available here: https://github.com/edx-solutions/edx-platform/pull/371

I have also added the commit with the test case to this branch.

**Comment by mtyaka** [comment]
LGTM

**Comment by antoviaque** [comment]
:+1:

**Pull request merged**
