### PR TITLE
Test CircleCI Builds

### PR DESCRIPTION
**Pull request by Kelketek**
Now that cypress-rebase is master, check to make sure it's possible for builds to be green, and make any final adjustments if not.

### CODE REVIEW

**Comment by Kelketek** [comment]
@smarnach @bradenmacdonald @antoviaque @smagoun Behold! It is now possible to get a clean build.

**Comment by smarnach** [comment]
Great!  I'm glad we got there, well done!

**Comment by bradenmacdonald** [comment]
Congratulations! This is going to be a big help.

**Comment by smagoun** [comment]
:trophy:

**Comment by antoviaque** [comment]
@Kelketek This is great! Kudos :D

**Pull request closed without merging**
