### PR TITLE
Update api-integration to 1.3.4.

### PR DESCRIPTION
**Pull request by mtyaka**
The new version includes changes from https://github.com/edx-solutions/api-integration/pull/70.

**Reviewers**:
- [x] @bogdanl

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx-solutions%2Fedx-platform&number=883"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by bogdanl** [comment]
This looks good to me.

**Comment by bradenmacdonald** [comment]
@mtyaka  @ziafazal the changes in https://github.com/edx-solutions/api-integration/pull/63 are causing two tests to fail due to an unexpected `group_id` parameter being passed to an API:

```
======================================================================
FAIL: test_follow_unfollow_thread_signals_1___follow_thread____thread_followed__ (lms.djangoapps.django_comment_client.base.tests.ViewsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/ddt.py", line 114, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/mock.py", line 1618, in _inner
    return f(*args, **kw)
  File "/home/ubuntu/edx-platform/lms/djangoapps/django_comment_client/base/tests.py", line 616, in test_follow_unfollow_thread_signals
    self.create_thread_helper(mock_request)
  File "/home/ubuntu/edx-platform/lms/djangoapps/django_comment_client/base/tests.py", line 435, in create_thread_helper
    timeout=5
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/mock.py", line 301, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: request('post', 'http://localhost:4567/api/v1/i4x-MITx-999-course-Robot_Super_Course/threads', data={'body': u'this is a post', 'anonymous_to_peers': False, 'user_id': 1, 'anonymous': False, 'context': 'course', 'title': u'Hello', 'course_id': u'MITx/999/Robot_Super_Course', 'thread_type': 'discussion', 'commentable_id': u'i4x-MITx-999-course-Robot_Super_Course'}, params={'request_id': <ANY>}, timeout=5, headers=<ANY>)
Actual call: request('post', u'http://localhost:4567/api/v1/i4x-MITx-999-course-Robot_Super_Course/threads', params={'request_id': UUID('45415d77-b069-48fe-850d-1ea7edfbec56')}, data={'body': u'this is a post', 'anonymous_to_peers': False, 'user_id': 1, 'anonymous': False, 'title': u'Hello', 'thread_type': u'discussion', 'commentable_id': u'i4x-MITx-999-course-Robot_Super_Course', 'context': 'course', 'course_id': u'MITx/999/Robot_Super_Course', 'group_id': 1}, timeout=5.0, headers={'X-Edx-Api-Key': None, 'Accept-Language': 'en'})
-------------------- >> begin captured logging << --------------------
openedx.core.djangoapps.safe_sessions.middleware: DEBUG: SafeCookieData received empty user_id 'None' for session_id '3izg8v2gl7ru0hn0qlqwgk7nwdcku2a0'.
audit: INFO: Login success - student (student@edx.org)
tracking: INFO: {"username": "student", "event_type": "/courses/MITx/999/Robot_Super_Course/discussion/i4x-MITx-999-course-Robot_Super_Course/threads/create", "ip": "127.0.0.1", "agent": "", "host": "testserver", "referer": "", "accept_language": "", "event": "{\"POST\": {\"body\": [\"this is a post\"], \"anonymous_to_peers\": [\"false\"], \"anonymous\": [\"false\"], \"title\": [\"Hello\"], \"thread_type\": [\"discussion\"], \"auto_subscribe\": [\"false\"]}, \"GET\": {}}", "event_source": "server", "context": {"course_user_tags": {}, "user_id": 1, "org_id": "MITx", "course_id": "MITx/999/Robot_Super_Course", "path": "/courses/MITx/999/Robot_Super_Course/discussion/i4x-MITx-999-course-Robot_Super_Course/threads/create"}, "time": "2017-09-18T21:37:43.713650+00:00", "page": null}
django_comment_client.base.views: DEBUG: Creating new thread in u'MITx/999/Robot_Super_Course', id u'i4x-MITx-999-course-Robot_Super_Course'
django_comment_client.utils: DEBUG: is_commentable_cohorted(MITx/999/Robot_Super_Course, i4x-MITx-999-course-Robot_Super_Course) = {True}
openedx.core.djangoapps.course_groups.models: INFO: Saving CohortMembership for user '1' in 'MITx/999/Robot_Super_Course'
lms.lib.comment_client.utils: INFO: comment_client_request_log: request_id=45415d77-b069-48fe-850d-1ea7edfbec56, method=post, url=http://localhost:4567/api/v1/i4x-MITx-999-course-Robot_Super_Course/threads, duration=0.000266075134277
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_follow_unfollow_thread_signals_2___unfollow_thread____thread_unfollowed__ (lms.djangoapps.django_comment_client.base.tests.ViewsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/ddt.py", line 114, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/mock.py", line 1618, in _inner
    return f(*args, **kw)
  File "/home/ubuntu/edx-platform/lms/djangoapps/django_comment_client/base/tests.py", line 616, in test_follow_unfollow_thread_signals
    self.create_thread_helper(mock_request)
  File "/home/ubuntu/edx-platform/lms/djangoapps/django_comment_client/base/tests.py", line 435, in create_thread_helper
    timeout=5
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/mock.py", line 301, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: request('post', 'http://localhost:4567/api/v1/i4x-MITx-999-course-Robot_Super_Course/threads', data={'body': u'this is a post', 'anonymous_to_peers': False, 'user_id': 1, 'anonymous': False, 'context': 'course', 'title': u'Hello', 'course_id': u'MITx/999/Robot_Super_Course', 'thread_type': 'discussion', 'commentable_id': u'i4x-MITx-999-course-Robot_Super_Course'}, params={'request_id': <ANY>}, timeout=5, headers=<ANY>)
Actual call: request('post', u'http://localhost:4567/api/v1/i4x-MITx-999-course-Robot_Super_Course/threads', params={'request_id': UUID('5844d574-fecb-468a-8ff3-fa5c0279e282')}, data={'body': u'this is a post', 'anonymous_to_peers': False, 'user_id': 1, 'anonymous': False, 'title': u'Hello', 'thread_type': u'discussion', 'commentable_id': u'i4x-MITx-999-course-Robot_Super_Course', 'context': 'course', 'course_id': u'MITx/999/Robot_Super_Course', 'group_id': 1}, timeout=5.0, headers={'X-Edx-Api-Key': None, 'Accept-Language': 'en'})
-------------------- >> begin captured logging << --------------------
```

**Comment by ziafazal** [comment]
@bradenmacdonald  @mtyaka PR #885 removes flakiness in the above mentioned tests.

**Comment by mtyaka** [comment]
Thanks @ziafazal!

**Pull request merged**
