### PR TITLE
Add indexes to 'modified' and 'completions' on StudentProgress model.

### PR DESCRIPTION
**Pull request by Kelketek**
Add indexes to the StudentProgress model for performance, per https://openedx.atlassian.net/browse/YONK-215

@bradenmacdonald @smarnach Please review at first opportunity.

### CODE REVIEW

**Comment by smarnach** [comment]
:+1: Code changes look good.  I ran the migration forward and backward, no issues.

Is there any reason to have this in the solutions fork only, or can we send this upstream as well?

**Comment by Kelketek** [comment]
@smarnach The progress app is Solutions only.

**Comment by smarnach** [comment]
@Kelketek Thanks, I accept this as a reason not to send this upstream.

**Comment by bradenmacdonald** [comment]
:+1:

**Pull request merged**
