### PR TITLE
[MCKIN-27010] Update xblock-eoc-journal to fix import issue

### PR DESCRIPTION
**Pull request by xitij2000**
Update xblock-eoc-journal to include this PR: https://github.com/open-craft/xblock-eoc-journal/pull/38

### CODE REVIEW

**Review by shimulch — APPROVED** [review]
LGTM :+1:

- [x] It's just a version upgrade for xblock-eoc-journal.
- [x] I read through the code
- [N/A] I checked for accessibility issues
- [N/A] Includes documentation
- [N/A] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

**Comment by xitij2000** [comment]
@ihtram Could you merge this if it seems OK? (I  can merge but given the test situation I was asked to ping you)

**Comment by ihtram** [comment]
@xitij2000 sure. I will merge it and will test on local docker environment. will update you after verification.

**Comment by ihtram** [comment]
@xitij2000 sure. I will merge it and will test on local docker environment. will update you after verification.

**Pull request merged**
