### PR TITLE
Add xblock-poll to optional apps

### PR DESCRIPTION
**Pull request by bradmerlin**
Adds [xblock-poll](https://github.com/open-craft/xblock-poll) to `OPTIONAL_APPS`. Required by https://github.com/open-craft/xblock-poll/pull/35

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bradmerlin! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx-solutions%2Fedx-platform&number=897"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by cgopalan** [comment]
:+1:

- [x] I tested this: Tested that if exporting poll and surveys csvs (https://github.com/open-craft/xblock-poll/pull/35) is done asynchronously using celery, then this change is necessary. Otherwise we get a `KeyError: u'poll.tasks.export_csv_data'` since celery does not recognize the export task added.
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~
- [x] ~~Includes documentation~~

**Comment by bradmerlin** [comment]
@bradenmacdonald Please merge when you have the time.

**Comment by bradenmacdonald** [comment]
@bradmerlin I'll wait until we can do the version bump at the same time, no?

**Comment by bradenmacdonald** [comment]
Rebased, added version bump, and now waiting for CI before we merge.

**Comment by bradenmacdonald** [comment]
Need to fix #942 before this will pass...

**Comment by bradenmacdonald** [comment]
Rebased - waiting for build.

**Pull request merged**
