### PR TITLE
Bump image explorer version to 1.1.1

### PR DESCRIPTION
**Pull request by jcdyer**
This contains a version bump for xblock-image-explorer.  It resolves the issue with image-explorer blocks being completed to early.  A similar problem for polls and surveys has already been resolved.

**JIRA tickets**: Implements BB-590

**Discussions**: N/A

**Dependencies**: None

**Screenshots**:

**Sandbox URL**: TBD - sandbox is being provisioned.

**Merge deadline**: None

**Testing instructions**:

Install the latest requirements: Create a course that has a poll, survey and image-explorer block. 

In studio (log in as staff w/ password edx): 

1. Go into advanced settings and add {{"poll", "survey", "image-explorer"}} to the list of advanced xblock types.  (Note, the list has to be a valid JSON list: double quotes only, no trailing comma, square brackets around the whole thing).
2. Then go into the course outline, and create a new chapter, section, and unit, and inside the unit add three blocks, one of each type (poll, survey, image explorer).  Go ahead and use the default configuration for each block.
3. Hit publish the course.
4. You might need to update the course start date, so it's already started.

For the next section, I found it helpful to add a print statement to completion/models.py at the beginning of "submit_completion", so you can see exactly when each block gets completed.  Something like:

```python
print("***", user, block_key.block_type, block_key)
```

You can also open up a manage.py lms shell, and do:

```python
>>> from completion.models import BlockCompletion
>>> BlockCompletion.objects.filter(block_type__in=["poll", "survey", "image-explorer"])
```

In the LMS,

1. Navigate to the unit that has your blocks.
2. Verify that no BlockCompletions have been created for your new blocks.
3. Answer the poll
4. Verify that a BlockCompletion was created for the poll.
5. Answer the survey
6. Verify the a BlockCompletion was created for the survey.
7. Click around the image-explorer.
8. Verify that a BlockCompletion was created for the image-explorer.

**Author notes and concerns**:

1. We are aware that there is a glitch affecting the UI for this feature in the following way: ...
   Currently looking for ways to fix it.
2. We tried to optimize for accessibility, but there are still some open questions: ...

**Reviewers**
- [ ] (OpenCraft internal reviewer's GitHub username goes here)
- [ ] edX reviewer[s] TBD

**Settings**
```yaml
EDXAPP_FEATURES:
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
```

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @jcdyer! I've created [OSPR-2859](https://openedx.atlassian.net/browse/OSPR-2859) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by giovannicimolin** [comment]
:+1:

- [x] I tested this: 
1. Enabled completions using `completion.enable_completion_tracking` waffle flag.
2. Created a new unit with three blocks, one of each type (poll, survey, image explorer).
3. Published the course and set dates.
4. Opened the LMS and the section created.
5. Checked that there were no BlockCompletion Objects.
Using (on Django Shell): 
```
from completion.models import BlockCompletion
BlockCompletion.objects.filter(block_type__in=["poll", "survey", "image-explorer"])
```
6. Answered the poll.
7. Checked that a BlockCompletion refering to the poll was created. 
8. Answered the survey.
9. Checked that a BlockCompletion refering to the survey was created.
10. Clicked around the image explorer.
11. Checked that a BlockCompletion refering to the image explorer was created.

- [x] I read through the code
~~- [ ] I checked for accessibility issues~~ NA
~~- [ ] Includes documentation~~ NA

**Comment by giovannicimolin** [comment]
@natabene This is ready for you review and testing.

**Comment by wajeeha-khalid** [comment]
@jcdyer  Can you please help me identify MCKIN board Jira ticket number against this work? I need this info to prepare release

**Comment by jcdyer** [comment]
This was a follow-up to resolve MCKIN-8752

**Pull request merged**
