### PR TITLE
Enable completion and completion aggregator repos

### PR DESCRIPTION
**Pull request by jcdyer**
This pulls openedx-completion-aggregator

**JIRA tickets**: OC-4474

**Discussions**: --

**Dependencies**: #1072, https://github.com/open-craft/openedx-completion-aggregator/pull/11

**Screenshots**:

**Sandbox URL**: N/A (Solutions)

**Merge deadline**: None

**Testing instructions**:

1. Fire up a ginkgo devstack with this branch.
2. Set the completion.enable_completion_tracking waffle switch.
3. Verify the site isn't broken.  Verify that creating a block completion triggers creation of a set of Aggregators.  Note: Not all blocks will create aggregators yet.  Try watching a video to the end, or manually creating a block completion.

**Author notes and concerns**:
**Reviewers**
- [ ] @afzaledx

**Settings**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @jcdyer! I've created [OSPR-2403](https://openedx.atlassian.net/browse/OSPR-2403) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by jcdyer** [comment]
@afzaledx I'm looking into it.  Thanks.

**Comment by jcdyer** [comment]
@afzaledx The problem was on my side.  There were two broken pieces.  I think I must have been done my final round of testing on the wrong branch.  The first problem was that the aggregator code was expecting the block transformers to be provided by a function, but ginkgo only had a constant.  So I added a function to match the newer api. (see commit:136e71a).  

The other problem was that old-style block keys don't contain all the data from the related course key, and this was breaking the ability to find the keys in the block structure, which meant that aggregators weren't being found for those course.

Old style block keys are ones that look like `idx://{org}/{course}/{block_type}/{block_id}` and correspond to course keys that look like `{org}/{course}/{run}`.  New style block keys look like `block-v1:{org}+{course}+{run}+type@{block_type}+block@{block_id}`.  Notice that the old style block keys don't have "{run}" information associated with them.   It turns out that even though the string representation lacks that information, the data objects sometimes have that information and sometimes don't, and ones that have course-run information don't compare equal to ones without that information.

I've fixed both those problems now, and manually tested the connection using the following script:

```python
"""
test.py
"""
from __future__ import absolute_import, division, print_function, unicode_literals

from completion.models import BlockCompletion
from completion_aggregator.models import Aggregator
from completion_aggregator import signals
from django.contrib.auth.models import User
from opaque_keys.edx.keys import CourseKey, UsageKey

def run():
    course = CourseKey.from_string('edX/PS101/20180506')
    block = UsageKey.from_string('i4x://edX/PS101/html/31d6a9882fc34ff5981f127b13ff8064').map_into_course(course)
    user = User.objects.get(username='verified')

    BlockCompletion.objects.all().delete()
    Aggregator.objects.all().delete()

    signals.register()

    BlockCompletion.objects.submit_completion(
        user=user,
        course_key=course,
        block_key=block,
        completion=0.8
    )
    for agg in Aggregator.objects.all():
        print agg.earned, agg.last_modified, agg. agg.block_type, agg.block_id
```
You may need to change the block key and course key strings to match real keys in a course on your stack.  I ran this by doing 
```sh
$ ./manage.py lms --settings=devstack shell
>>> import test
>>> test.run()
```

The output should list all the course aggregators (verticals, sequentials, chapters, and course), most of which will list a value of 0.0, but one of each category will say 0.8.

**Comment by jcdyer** [comment]
@afzaledx The problem was on my side.  There were two broken pieces.  I think I must have been done my final round of testing on the wrong branch.  The first problem was that the aggregator code was expecting the block transformers to be provided by a function, but ginkgo only had a constant.  So I added a function to match the newer api. (see commit:136e71a).  

The other problem was that old-style block keys don't contain all the data from the related course key, and this was breaking the ability to find the keys in the block structure, which meant that aggregators weren't being found for those course.

Old style block keys are ones that look like `idx://{org}/{course}/{block_type}/{block_id}` and correspond to course keys that look like `{org}/{course}/{run}`.  New style block keys look like `block-v1:{org}+{course}+{run}+type@{block_type}+block@{block_id}`.  Notice that the old style block keys don't have "{run}" information associated with them.   It turns out that even though the string representation lacks that information, the data objects sometimes have that information and sometimes don't, and ones that have course-run information don't compare equal to ones without that information.

I've fixed both those problems now, and manually tested the connection using the following script:

```python
"""
test.py
"""
from __future__ import absolute_import, division, print_function, unicode_literals

from completion.models import BlockCompletion
from completion_aggregator.models import Aggregator
from completion_aggregator import signals
from django.contrib.auth.models import User
from opaque_keys.edx.keys import CourseKey, UsageKey

def run():
    course = CourseKey.from_string('edX/PS101/20180506')
    block = UsageKey.from_string('i4x://edX/PS101/html/31d6a9882fc34ff5981f127b13ff8064').map_into_course(course)
    user = User.objects.get(username='verified')

    BlockCompletion.objects.all().delete()
    Aggregator.objects.all().delete()

    signals.register()

    BlockCompletion.objects.submit_completion(
        user=user,
        course_key=course,
        block_key=block,
        completion=0.8
    )
    for agg in Aggregator.objects.all():
        print agg.earned, agg.last_modified, agg. agg.block_type, agg.block_id
```
You may need to change the block key and course key strings to match real keys in a course on your stack.  I ran this by doing 
```sh
$ ./manage.py lms --settings=devstack shell
>>> import test
>>> test.run()
```

The output should list all the course aggregators (verticals, sequentials, chapters, and course), most of which will list a value of 0.0, but one of each category will say 0.8.

**Comment by afzaledx** [comment]
@jcdyer , stil doesnt work for me.
I tried to run your script after changing the course/block/user. Firstly, I had to remove the last three , agg. agg.block_type, agg.block_id since it complained that the agg did not have block_id and block_type. It did print the gg.earned, agg.last_modified, but all were 0.0, and the date was 1900
0.0 1900-01-01 00:00:00+00:00
0.0 1900-01-01 00:00:00+00:00
0.0 1900-01-01 00:00:00+00:00
0.0 1900-01-01 00:00:00+00:00
0.0 1900-01-01 00:00:00+00:00
0.0 1900-01-01 00:00:00+00:00

Moreover, the aggregate api did not show any proper data. the completion api worked fine:

After running the test.py, the output of the aggregate api changed a bit:

"completion": {
"earned": 0,
"possible": 3,
"percent": 0


from the previous 0/null/null

"completion": {
"earned": 0,
"possible": null,
"percent": null

Also, as previously, I got the paginator error because of 1.2.2 -> 1.2.4

The server log stop giving the error it was giving previously.

One last thing:

After running all the requirements, when I did pip freeze, it showed  aggregaotr==0.1.0
whereas I had expected it to be 0.1.1

git+https://github.com/open-craft/openedx-completion-aggregator@cliff/ginkgo-compat#egg=openedx-completion-aggregator==0.1.1

I have spent a long time on it figuring out what's wrong, but I am not sure.

**Comment by jcdyer** [comment]
First easy part: agg.block_id and agg.block_type should have been agg.block.*.  My mistake.  I edited after I copy-pasted, which is always a mistake.  I'm looking into your other issues.

**Comment by jcdyer** [comment]
Second, fairly easy part: The version doesn't match because pip doesn't care what you tell it.  It uses the value in setup.py, which is still 0.1.0, because the code is on a branch, not yet released, so I haven't updated it.  As long as you are installing the ginkgo-compat branch, it should be fine.

**Comment by jcdyer** [comment]
Third, when I updated edx-drf-extensions, I started getting a number of errors around translation in a field object in django-rest-framework.  I remember seeing this error during initial development, and I don't remember the solution, so instead of resolving this, I kept edx-drf-extensions pinned to 1.2.2, and updated the aggregator code to conditionally import the paginator from edx-platform, where it lived before.  After doing that, and reinstalling all prereqs (`NO_PREREQ_INSTALL= paver install_prereqs; pip install git+https://github.com/open-craft/openedx-completion-aggregator@cliff/ginkgo-compat`), I started getting the expected values from the aggregator endpoint.

Specifically, I visited a problem_builder problem, submitted an answer, and then checked the completion-aggregator course endpoint (http://localhost:8000/api/completion-aggregator/v1/course/edX/PS101/20180506/?requested_fields=chapter), and the earned value increased on the relevant course and chapter level aggregators.

**Comment by jcdyer** [comment]
Ready for another review.

**Comment by afzaledx** [comment]
@jcdyer,

here are the exact steps that I did:
I checked out the branch cliff/enable-completion
ran these:

sudo su edxapp
unset NO_PREREQ_INSTALL
git clean -fx
paver install_prereqs
./manage.py lms migrate --settings=devstack

(enabled the waffle switch)

placed the test.py next to manage.py

with these contents:
```
def run():
    course = CourseKey.from_string('afzalx/cs108/2018_T1')
    block = UsageKey.from_string('i4x://afzalx/cs108/vertical/60db46de830a4577b6c468c83632e866').map_into_course(course)

    user = User.objects.get(username='verified')

    BlockCompletion.objects.all().delete()
    Aggregator.objects.all().delete()

    signals.register()

    BlockCompletion.objects.submit_completion(
        user=user,
        course_key=course,
        block_key=block,
        completion=0.8
    )

    for completion in BlockCompletion.objects.all():
        print (completion)

    for agg in Aggregator.objects.all():
        print (agg)
```

This is the output I received:
```
2018-06-04 11:04:25,690 INFO 14732 [completion_aggregator.signals] signals.py:41 - COHORT_MEMBERSHIP_UPDATED signal not found. If this is a solutions/ginkgo server, this is expected.
2018-06-04 11:04:25,694 INFO 14732 [completion_aggregator.signals] signals.py:48 - ENROLLMENT_TRACK_UPDATED signal not found. If this is a solutions/ginkgo server, this is expected.
2018-06-04 11:04:25,796 INFO 14732 [completion_aggregator.tasks] tasks.py:63 - Updating aggregators in afzalx/cs108/2018_T1 for verified. Changed blocks: set([BlockUsageLocator(CourseLocator(u'afzalx', u'cs108', u'2018_T1', None, None), u'vertical', u'60db46de830a4577b6c468c83632e866')])
2018-06-04 11:04:25,798 INFO 14732 [openedx.core.djangoapps.content.block_structure.store] store.py:176 - BlockStructure: Read from cache; <openedx.core.djangoapps.content.block_structure.store.StubModel object at 0x7fd1394a4510>, size: 2597
BlockCompletion: verified, afzalx/cs108/2018_T1, i4x://afzalx/cs108/vertical/60db46de830a4577b6c468c83632e866: 0.8
Aggregator: verified, afzalx/cs108/2018_T1, i4x://afzalx/cs108/vertical/60db46de830a4577b6c468c83632e866: 0.0
Aggregator: verified, afzalx/cs108/2018_T1, i4x://afzalx/cs108/sequential/45296e9b6b5d47c0a5d3378bd0c93185: 0.0
Aggregator: verified, afzalx/cs108/2018_T1, i4x://afzalx/cs108/chapter/02200e785eec427fb0e1fa540eb67352: 0.0
Aggregator: verified, afzalx/cs108/2018_T1, i4x://afzalx/cs108/course/2018_T1: 0.0
```

**Comment by afzaledx** [comment]
👍 I have tested it. @jcdyer , thanks for helping me test it.

**Pull request merged**
