### PR TITLE
updated polls xblock version on mcka

### PR DESCRIPTION
**Pull request by zvishal**
to allow for generic messages (copy changes only)

### CODE REVIEW

**Comment by zvishal** [comment]
@bradenmacdonald updated the version. this good?

**Comment by bradenmacdonald** [comment]
👍 

LGTM Vishal. I can't test this properly on my devstack right now since it's been upgraded for the Eucalyptus rebase, but I confirmed that this new requirements line works and installs the correct version.

**Comment by bradenmacdonald** [comment]
@ziafazal Why are all the CircleCI builds failing on this repo? Is it something to do with the rebase?

**Comment by ziafazal** [comment]
@bradenmacdonald CircleCI build should pass on this branch since it does not have Euclayptus updates. I think CircleCI build is failing due to this 
https://discuss.circleci.com/t/bundle-command-not-found/3783

**Comment by bradenmacdonald** [comment]
@zvishal Despite the failing tests, I think this tiny PR is safe to merge, so let's merge now and confirm on QA. I've opened https://github.com/edx-solutions/edx-platform/pull/754 to partially fix the failing tests, but there are others that are failing. If we're planning to make more changes to this repository before the Eucalyptus rebase is done, I'd recommend that we make sure someone addresses those tests and we get back to having test runs and green builds on each change. If you want my team to do that we'd be happy to. Merging platform changes without CI is risky and decreases our overall productivity.

**Pull request merged**
