### PR TITLE
Version bump of studio-frontend.

### PR DESCRIPTION
**Pull request by attiyaIshaque**
### Description
 On uploading a file bigger than 10mb the context line is saying.

` **The maximum size for an upload is 10,000,000 MB. No files were uploaded.**`
But the message should be 
`**The maximum size for an upload is 10 MB. No files were uploaded.**`
And I have changed in this PR https://github.com/edx/studio-frontend/pull/288 which creates the tag version **`1.16.22`**

In the Ironwood release we uses the version of Studio-frontend **`1.16.14`**.
These are the versions which has been created after the ironwood. https://github.com/edx/studio-frontend/compare/v1.16.14...v1.16.22.

@fysheets What is the impact of these changes in the studio side? Should we go with these changes with the ironwood? Need your suggestion here.

### CODE REVIEW

**Comment by attiyaIshaque** [comment]
Hi @fysheets, I have updated the version from `1.16.14` to `1.16.22. ` Studio-frontend version 1.16.14 is used in Ironwood. The versions which has been created after the ironwood, how we managed these versions with the ironwood?

**Comment by fysheets** [comment]
Hey Attiya, I'm not sure. I would potentially sync with Ned on best practices here.

**Comment by attiyaIshaque** [comment]
@natabene Can you please look?

**Comment by natabene** [comment]
@nedbat Can we get this into Juniper?

**Comment by nedbat** [comment]
There's no explanation here about why this should be applied to Juniper. What does it fix?

**Comment by attiyaIshaque** [comment]
@nedbat I have updated the description of the PR. Can you please see it?

**Comment by nedbat** [comment]
Let's have a separate discussion about Juniper on a new pull request.  This is moving from .14 to .22, which sounds like many more changes than just fixing an error message.

**Comment by attiyaIshaque** [comment]
@nedbat Is there any way we get change from .22 to .14? OR any other solution you would recommend? Or we can fork this Repo?

**Comment by fysheets** [comment]
Looking at https://github.com/edx/studio-frontend/compare/v1.16.14...v1.16.22 - it looks like these are mostly smaller changes related to translations, another open PR, a bug fix, and now Attiya's bug fix. I would see no reason why these would not benefit our open members.

**Comment by nedbat** [comment]
I would be happy to look at a pull request that updates open-release/juniper.master.  That branch has 1.16.19 now.  I don't know how to properly update these files myself, and this pull request does not start from 1.16.19, so we can't simply cherry-pick it.

**Comment by natabene** [comment]
@nedbat What would the next steps be for us ?

**Comment by nedbat** [comment]
Someone needs to make a pull request against the open-release/juniper.master branch.

**Comment by attiyaIshaque** [comment]
@nedbat I will open a PR against `open-release/juniper.master` branch.

**Pull request merged**
