### PR TITLE
MCKIN-7030 Add student_view_data to PB Recap components

### PR DESCRIPTION
**Pull request by bradenmacdonald**
This pulls in https://github.com/open-craft/problem-builder/pull/180

### CODE REVIEW

**Comment by e-kolpakov** [comment]
@bradenmacdonald There are a few quality violations (10 lines out of 100K lines) and some test failures - while they seem to be irrelevant to the change, I don't think it's a god idea if I just merge it now. Please consider my approval as "I'm ok with the change and don't think Ci failures are relevant", but please take a look yourself and consult with edx-solutions maintainers, if necessary.

Not merging just now.

**Comment by bradenmacdonald** [comment]
@wajeeha-khalid  Is someone from your team working on the test + quality failures on the rebased `integration` branch?

**Comment by wajeeha-khalid** [comment]
@bradenmacdonald We have not yet rebased platform but only Apros for now.
@ihtram from EdX is working on rebasing platform `integration` with `master` branch.
We will et you know once it is done.

**Comment by ihtram** [comment]
@bradenmacdonald The quality issues came after rebasing ginkgo. These issues will be resolved once we merge integration branch in master. I think it is okay to ignore quality failures and merge this branch.

**Comment by bradenmacdonald** [comment]
Ok, merging now.

**Pull request merged**
