### PR TITLE
Restored custom requirements to pre-rebase state

### PR DESCRIPTION
**Pull request by e-kolpakov**
@ziafazal Looks like after rebasing some custom XBlock dependencies were lost or rolled back to outdated versions - restoring them.

Also, switched back to edx-solutions version of XBlock and switched discussion to use UNIQUE_ID for discussion_id

**Dependency:** https://github.com/edx-solutions/edx-platform/pull/412

### CODE REVIEW

**Comment by Kelketek** [comment]
@e-kolpakov I think this may need to be rebased again? I don't just see your commits, but some from @ziafazal as well.

**Comment by e-kolpakov** [comment]
@Kelketek it's a bit more complicated than that. This PR is against main rebase branch, but it does not work as is - there's separate @ziafazal [PR](https://github.com/edx-solutions/edx-platform/pull/412) with three commits you can see here. Those three commits are post-rebase fixes, So this PR should be merged only after that PR. I'll add a dependency here.

**Comment by Kelketek** [comment]
@e-kolpakov Alright, then. This looks alright to me. :+1:

**Comment by e-kolpakov** [comment]
@ziafazal  you might want to take a look at this as a second reviewer.

**Comment by ziafazal** [comment]
@e-kolpakov LGTM :+1:

**Comment by e-kolpakov** [comment]
@ziafazal thank you. As you can see it depends on other PR, so I'm not able to merge it now - please ping me when #412 is merged.

**Comment by ziafazal** [comment]
@smagoun @antoviaque  what are the next steps? It looks like review is done. Should we merge it to master?

**Comment by e-kolpakov** [comment]
@ziafazal not before the dependency PR #412

**Comment by bradenmacdonald** [comment]
@e-kolpakov Can you please also bump xblock-utils to 8193ee7eb7a94d339435fdceb57e63964d271c3d (latest edx upstream master) as part of this PR? It will be needed for mentoring v2. Should have no backwards compatibility issues.

**Comment by e-kolpakov** [comment]
@bradenmacdonald added 8193ee7eb7a94d339435fdceb57e63964d271c3d

**Comment by bradenmacdonald** [comment]
Thanks @e-kolpakov

**Comment by ziafazal** [comment]
@e-kolpakov closing this since we have PR #426 already merged.

**Pull request closed without merging**
