### PR TITLE
Group Project V2 hash update

### PR DESCRIPTION
**Pull request by e-kolpakov**

### CODE REVIEW

**Comment by naeem91** [comment]
@ziafazal Would you please reveiw review so it could be merged and available for pentest revalidation which has started today.

**Comment by ziafazal** [comment]
@naeem91 it seems we have version conflict which is failing CircleCI built. I have started the build again without cache if it fixes it. Here is the error
```
 raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (edx-opaque-keys 0.2.1 (/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages), Requirement.parse('edx-opaque-keys<1.0.0,>=0.4.0'), set(['XModule']))

pip install --exists-action w -r requirements/edx/local.txt returned exit code 2

Action failed: pip install --exists-action w -r requirements/edx/local.txt
```

**Comment by ziafazal** [comment]
@naeem91 we are good to merge now.

**Comment by bradenmacdonald** [comment]
Merged. Thanks @ziafazal @naeem91 @e-kolpakov !

**Pull request merged**
