### PR TITLE
Added last_login field to user api

### PR DESCRIPTION
**Pull request by kotky**
Currently for user details there doesn't exist any way to get last login date. For our client we need to get last login date. We hope that you can merge this commit with master.

### CODE REVIEW

**Comment by smagoun** [comment]
@ziafazal can you review this?

@kotky are there any tests for this functionality?

**Comment by ziafazal** [comment]
@kotky please update add new test to support your change.

**Comment by zvishal** [comment]
@kotky @dino-cikatic can you please reply to @ziafazal 's question? Let us know if you are able to add a new test.

**Comment by zvishal** [comment]
@ziafazal seems like the tests have been added already per the code update below: please confirm if we need any more updates.
https://github.com/edx-solutions/edx-platform/commit/6fa5d17ededf5f1b664289c310153913f0b84a82

CC @kotky @dino-cikatic @smagoun

**Comment by ziafazal** [comment]
@zvishal closing this in favour of PR #667. Since same change has been already merged in master.

**Pull request closed without merging**
