### PR TITLE
[MCKIN-9028] Downgrade `discussion-edx-platform-extensions`

### PR DESCRIPTION
**Pull request by Agrendalath**
Optimized `discussion-edx-platform-extensions` is not meant to go to the next prod release, so we should bump it back to v1.2.8 for now.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Agrendalath! I've created [OSPR-2863](https://openedx.atlassian.net/browse/OSPR-2863) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by viadanna** [comment]
@Agrendalath This will need changes to the `api-integration` as the version in use needs `v1.2.9`:
```
    data = StudentSocialEngagementScore.get_course_engagement_scores(course_key, organization, exclude_users)
AttributeError: type object 'StudentSocialEngagementScore' has no attribute 'get_course_engagement_scores'
```

Let me check that out.

**Comment by Agrendalath** [comment]
Thanks for noticing this, @viadanna!
I didn't have too much context on `api-integration` reverts now.

**Comment by viadanna** [comment]
@Agrendalath Yeah, it seems we'll have to downgrade `api-integration` to v2.3.1 and revert the cohort average scores at that point. I'll start working on that now.

**Comment by Agrendalath** [comment]
@viadanna, thanks!

**Pull request merged**
